;;;;;;;;;;;;;;;;;;;;;;;;
; SDL2 AutoIt3 Wrapper ;
; Wrapper by: Andy P.  ;
;Icy Viking Games      ;
;For AutoIt3           ;
;Copyright (c) 2018    ;
;;;;;;;;;;;;;;;;;;;;;;;;

;SDL 2 Flags - Note Hex values are converted to decimal values

#include-once

;Init Flags
Global Const $SDL_INIT_TIMER = 1
Global Const $SDL_INIT_AUDIO = 16
Global Const $SDL_INIT_VIDEO = 32
Global Const $SDL_INIT_JOYSTICK = 512
Global Const $SDL_INIT_HAPTIC = 4096
Global Const $SDL_INIT_GAMECONTROLLER = 8192
Global Const $SDL_INIT_EVENTS = 16384
Global Const $SDL_INIT_NOPARACHUTE = 1048576
Global Const $SDL_INIT_EVERYTHING = $SDL_INIT_TIMER + $SDL_INIT_AUDIO + $SDL_INIT_VIDEO + $SDL_INIT_EVENTS + $SDL_INIT_JOYSTICK + $SDL_INIT_HAPTIC + $SDL_INIT_GAMECONTROLLER

;SDL2 Assert Flags
Global Enum $SDL_ASSERTION_RETRY, $SDL_ASSERTION_BREAK, $SDL_ASSERTION_ABORT, $SDL_ASSERTION_IGNORE, $SDL_ASSERTION_ALWAYS_IGNORE

;SDL2 Audio Flags
Global Const $SDL_AUDIO_MASK_BITSIZE = 255
Global Const $SDL_AUDIO_MASK_DATATYPE = 256
Global Const $SDL_AUDIO_MASK_ENDIAN = 4096
Global Const $SDL_AUDIO_MASK_SIGNED = 32768
Global Const $SDL_AUDIO_BITSIZE = $SDL_AUDIO_MASK_BITSIZE
Global Const $SDL_AUDIO_ISFLOAT = $SDL_AUDIO_MASK_DATATYPE
Global Const $SDL_AUDIO_ISBIGENDIAN = $SDL_AUDIO_MASK_ENDIAN
Global Const $SDL_AUDIO_ISSIGNED = $SDL_AUDIO_MASK_SIGNED
Global Const $SDL_AUDIO_ISINT = $SDL_AUDIO_ISFLOAT
Global Const $SDL_AUDIO_ISLITTLEENDIAN = -$SDL_AUDIO_ISBIGENDIAN
Global Const $SDL_AUDIO_ISUNSIGNED = -$SDL_AUDIO_ISSIGNED

;SDL2 Video Flags
Global Const $SDL_WINDOW_FULLSCREEN = 1
Global Const $SDL_WINDOW_OPENGL = 2
Global Const $SDL_WINDOW_SHOWN = 4
Global Const $SDL_WINDOW_HIDDEN = 8
Global Const $SDL_WINDOW_BORDERLESS = 16
Global Const $SDL_WINDOW_RESIZABLE = 32
Global Const $SDL_WINDOW_MINIMIZED = 64
Global Const $SDL_WINDOW_MAXIMIZED = 128
Global Const $SDL_WINDOW_INPUT_GRABBED = 256
Global Const $SDL_WINDOW_INPUT_FOCUS = 512
Global Const $SDL_WINDOW_MOUSE_FOCUS = 1024
Global Const $SDL_WINDOW_FULLSCREEN_DESKTOP = BitOR($SDL_WINDOW_FULLSCREEN, 256)
Global Const $SDL_WINDOW_FOREIGN = 2048
Global Const $SDL_WINDOW_HIGHDPI = 8192
Global Const $SDL_WINDOW_ALWAYS_ON_TOP = 32768

;Audio Flags Cont.
Global Const $AUDIO_U8 = 8
Global Const $AUDIO_S8 = 32776
Global Const $AUDIO_U16LSB = 16
Global Const $AUDIO_S16LSB = 32784
Global Const $AUDIO_U16MSB = 4112
Global Const $AUDIO_S16MSB = 36880
Global Const $AUDIO_U16 = $AUDIO_U16LSB
Global Const $AUDIO_S16 = $AUDIO_S16LSB

;Audio Flags Cont.
Global Const $AUDIO_S32LSB = 32800
Global Const $AUDIO_S32MSB = 36896
Global Const $AUDIO_S32 = $AUDIO_S32LSB

;Audio Flags Cont.
Global Const $AUDIO_F32LSB = 33056
Global Const $AUDIO_F32MSB = 37152
Global Const $AUDIO_F32 = $AUDIO_F32LSB

;Audio Flags Cont.
Global Const $AUDIO_U16SYS = $AUDIO_U16LSB
Global Const $AUDIO_S16SYS = $AUDIO_S16LSB
Global Const $AUDIO_S32SYS = $AUDIO_S32LSB
Global Const $AUDIO_F32SYS = $AUDIO_F32LSB

Global Const $SDL_AUDIO_ALLOW_FREQUENCY_CHANGE = 1
Global Const $SDL_AUDIO_ALLOW_FORMAT_CHANGE = 2
Global Const $SDL_AUDIO_ALLOW_CHANNELS_CHANGE = 4
Global Const $SDL_AUDIO_ALLOW_ANY_CHANGE = $SDL_AUDIO_ALLOW_FREQUENCY_CHANGE + $SDL_AUDIO_ALLOW_FORMAT_CHANGE + $SDL_AUDIO_ALLOW_CHANNELS_CHANGE

Global Enum $SDL_AUDIO_STOPPED, $SDL_AUDIO_PLAYING, $SDL_AUDIO_PAUSED

Global Const $SDL_MIX_MAXVOLUME = 128

;SDL2 Joystick Flags
Global Const $SDL_JOYSTICK_AXIS_MAX = 32767
Global Const $SDL_JOYSTICK_AXIS_MIN = -32768

;SDL2 Blend Flags
Global Enum $SDL_BLENDMODE_NONE, $SDL_BLENDMODE_BLEND,$SDL_BLENDMODE_ADD,$SDL_BLENDMODE_MOD = 4

Global Enum $SDL_BLENDOPERATION_ADD = 1, $SDL_BLENDOPERATION_SUBTRACT, $SDL_BLENDOPERATION_REV_SUBTRACT,$SDL_BLENDOPERATION_MINIMUM,$SDL_BLENDOPERATION_MAXIMUM

Global Enum $SDL_BLENDFACTOR_ZERO = 1, $SDL_BLENDFACTOR_ONE, $SDL_BLENDFACTOR_SRC_COLOR, $SDL_BLENDFACTOR_ONE_MINUS_SRC_COLOR, $SDL_BLENDFACTOR_SRC_ALPHA, $SDL_BLENDFACTOR_ONE_MINUS_SRC_ALPHA, $SDL_BLENDFACTOR_DST_COLOR, $SDL_BLENDFACTOR_ONE_MINUS_DST_COLOR, $SDL_BLENDFACTOR_DST_ALPHA, $SDL_BLENDFACTOR_ONE_MINUS_DST_ALPHA

Global Const $SDL_CACHELINE_SIZE = 128

;SDL2 Misc Flags
Global Const $SDL_LIL_ENDIAN = 1234
Global Const $SDL_BIG_ENDIAN = 4321

Global Enum $SDL_ENOMEM, $SDL_EFREAD, $SDL_EFWRITE, $SDL_EFSEEK, $SDL_UNSUPPORTED, $SDL_LASTERROR

Global Const $SDL_RELEASED = 0
Global Const $SDL_PRESSED = 1

;SDL2 Event Flags
Global Enum $SDL_FIRSTEVENT, $SDL_QUIT = 256, $SDL_APP_TERMINATING, $SDL_APP_LOWMEMORY, $SDL_APP_WILLENTERBACKGROUND, $SDL_DIDENTERBACKGROUND, $SDL_APP_WILLENTERFOREGROUND, $SDL_APP_DIDENTERFOREGROUND
Global Enum $SDL_WINDOWEVENT = 512, $SDL_SYSWMEVENT
Global Enum $SDL_KEYDOWN = 768, $SDL_KEYUP, $SDL_TEXTEDITING, $SDL_TEXTINPUT
Global Enum $SDL_MOUSEMOTION = 1024, $SDL_MOUSEBUTTONDOWN, $SDL_MOUSEBUTTONUP, $SDL_MOUSEWHEEL
Global Enum $SDL_JOYAXISMOTION = 1536, $SDL_JOYBALLMOTION, $SDL_JOYHATMOTION, $SDL_JOYBUTTONDOWN, $SDL_JOYBUTTONUP, $SDL_JOYDEVICEADDED, $SDL_JOYDEVICEREMOVED
Global Enum $SDL_CONTROLLERAXISMOTION = 1616, $SDL_CONTROLLERBUTTONDOWN, $SDL_CONTROLLERBUTTONUP, $SDL_CONTROLLERDEVICEADDED, $SDL_CONTROLLERDEVICEREMOVED, $SDL_CONTROLLERDEVICEREMAPPED
Global Enum $SDL_FINGERDOWN = 1792, $SDL_FINGERUP, $SDL_FINGERMOTION
Global Enum $SDL_DOLLARGESTURE = 2048, $SDL_DOLLARRECORD, $SDL_MULTIGESTURE
Global Enum $SDL_CLIPBOARDUPDATE = 2304, $SDL_DROPFILE = 4096, $SDL_RENDER_TARGETS_RESET = 8192, $SDL_USEREVENT = 32768, $SDL_LASTEVENT = 65535

Global Enum $SDL_ADDEVENT, $SDL_PEEKEVENT, $SDL_GETEVENT

Global Const $SDL_QUERY = -1
Global Const $SDL_IGNORE = 0
Global Const $SDL_DISABLE = 0
Global Const $SDL_ENABLE = 1

;Gamecontroller flags
Global Enum $SDL_CONTROLLER_BINDTYPE_NONE, $SDL_CONTROLLER_BINDTYPE_BUTTON, $SDL_CONTROLLER_BINDTYPE_AXIS, $SDL_CONTROLLER_BINDTYPE_HAT

Global Enum $SDL_CONTROLLER_AXIS_INVALID = -1, $SDL_CONTROLLER_AXIS_LEFTX,$SDL_CONTROLLER_AXIS_LEFTY,$SDL_CONTROLLER_RIGHTX,$SDL_CONTROLLER_RIGHTY,$SDL_CONTROLLER_AXIS_TRIGGERLEFT,$SDL_CONTROLLER_AXIS_TRIGGERRIGHT,$SDL_CONTROLLER_AXIS_MAX

Global Enum $SDL_CONTROLLER_BUTTON_INVALID = -1, $SDL_CONTROLLER_BUTTON_A,$SDL_CONTROLLER_BUTTON_B,$SDL_CONTROLLER_BUTTON_X,$SDL_CONTROLLER_BUTTON_Y,$SDL_CONTROLLER_BUTTON_BACK,$SDL_CONTROLLER_BUTTON_GUIDE,$SDL_CONTROLLER_BUTTON_START,$SDL_CONTROLLER_BUTTON_LEFTSTICK,$SDL_CONTROLLER_BUTTON_RIGHTSTICK, $SDL_CONTROLLER_BUTTON_LEFTSHOULDER,$SDL_CONTROLLER_BUTTON_RIGHTSHOULDER,$SDL_CONTROLLER_BUTTON_DPAD_UP,$SDL_CONTROLLER_BUTTON_DPAD_DOWN,$SDL_CONTROLLER_BUTTON_DPAD_LEFT,$SDL_CONTROLLER_BUTTON_DPAD_RIGHT,$SDL_CONTROLLER_BUTTON_MAX

;Haptic(rumble) flags
Global Const $SDL_HAPTIC_CONSTANT = 0
Global Const $SDL_HAPTIC_SINE = 2
Global Const $SDL_HAPTIC_LEFTRIGHT = 4
Global Const $SDL_HAPTIC_TRIANGLE = 8
Global Const $SDL_HAPTIC_SAWTOOTUP = 16
Global Const $SDL_HAPTIC_SAWTOOTHDOWN = 32
Global Const $SDL_HAPTIC_RAMP = 64
Global Const $SDL_HAPTIC_SPRING = 128
Global Const $SDL_HAPTIC_DAMPER = 256
Global Const $SDL_HAPTIC_INERTIA = 512
Global Const $SDL_HAPTIC_FRICTION = 1024
Global Const $SDL_HAPTIC_CUSTOM = 2048
Global const $SDL_HAPTIC_GAIN = 4096
Global Const $SDL_HAPTIC_AUTOCENTER = 8192
Global Const $SDL_HAPTIC_STATUS = 16384
Global Const $SDL_HAPTIC_PAUSE = 32768
Global Const $SDL_HAPTIC_POLAR = 0
Global const $SDL_HAPTIC_CARTESIAN = 1
Global Const $SDL_HAPTIC_SPHERICAL = 2
Global Const $SDL_HAPTIC_INFINITY = 285960729237

Global Enum $SDL_HINT_DEFAULT, $SDL_HINT_NORMAL, $SDL_HINT_OVERRIDE

;joystick flags
Global Const $SDL_HAT_CENTERED = 0
Global Const $SDL_HAT_UP = 1
Global Const $SDL_HAT_RIGHT = 2
Global Const $SDL_HAT_DOWN = 4
Global Const $SDL_HAT_LEFT = 8
Global const $SDL_RIGHTUP = BitOR($SDL_HAT_RIGHT,$SDL_HAT_UP)
Global Const $SDL_RIGHTDOWN = BitOR($SDL_HAT_RIGHT,$SDL_HAT_DOWN)
Global Const $SDL_LEFTUP = BitOR($SDL_HAT_LEFT,$SDL_HAT_UP)
Global Const $SDL_LEFTDOWN = BitOR($SDL_HAT_LEFT,$SDL_HAT_DOWN)

Global Const $SDLK_SCANCODE_MASK = 1073741824
Global Const $SDL_SCANCODE_TO_KEYCODE = $SDLK_SCANCODE_MASK

;Keycode Flags (in the C code it is declared as a enum, due to the way enums are handled in AutoIt, I'll be
               ;declaring them as global consts to make it easier)

Global Const $SDL_SCANCODE_UNKNOWN = 0
Global Const $SDL_SCANCODE_A = 4
Global Const $SDL_SCANCODE_B = 5
Global Const $SDL_SCANCODE_C = 6
Global Const $SDL_SCANCODE_D = 7
Global Const $SDL_SCANCODE_E = 8
Global Const $SDL_SCANCODE_F = 9
Global Const $SDL_SCANCODE_G = 10
Global Const $SDL_SCANCODE_H = 11
Global Const $SDL_SCANCODE_I = 12
Global Const $SDL_SCANCODE_J = 13
Global Const $SDL_SCANCODE_K = 14
Global Const $SDL_SCANCODE_L = 15
Global Const $SDL_SCANCODE_M = 16
Global Const $SDL_SCANCODE_N = 17
Global Const $SDL_SCANCODE_O = 18
Global Const $SDL_SCANCODE_P = 19
Global Const $SDL_SCANCODE_Q = 20
Global Const $SDL_SCANCODE_R = 21
Global Const $SDL_SCANCODE_S = 22
Global Const $SDL_SCANCODE_T = 23
Global Const $SDL_SCANCODE_U = 24
Global Const $SDL_SCANCODE_V = 25
Global Const $SDL_SCANCODE_W = 26
Global Const $SDL_SCANCODE_X = 27
Global Const $SDL_SCANCODE_Y = 28
Global Const $SDL_SCANCODE_Z = 29

Global Const $SDL_SCANCODE_1 = 30
Global Const $SDL_SCANCODE_2 = 31
Global Const $SDL_SCANCODE_3 = 32
Global Const $SDL_SCANCODE_4 = 33
Global Const $SDL_SCANCODE_5 = 34
Global Const $SDL_SCANCODE_6 = 35
Global Const $SDL_SCANCODE_7 = 36
Global Const $SDL_SCANCODE_8 = 37
Global Const $SDL_SCANCODE_9 = 38
Global Const $SDL_SCANCODE_0 = 39

Global Const $SDL_SCANCODE_RETURN = 40
Global Const $SDL_SCANCODE_ESCAPE = 41
Global Const $SDL_SCANCODE_BACKSPACE = 42
Global Const $SDL_SCANCODE_TAB = 43
Global Const $SDL_SCANCODE_SPACE = 44

Global Const $SDL_SCANCODE_MINUS = 45
Global Const $SDL_SCANCODE_EQUALS = 46
Global Const $SDL_SCANCODE_LEFTBRACKET = 47
Global Const $SDL_SCANCODE_RIGHTBRACKET = 48
Global Const $SDL_SCANCODE_BACKSLASH = 49

Global Const $SDL_SCANCODE_NONUSHASH = 50

Global Const $SDL_SCANCODE_SEMICOLON = 51
Global Const $SDL_SCANCODE_APOSTROPHE = 52
Global Const $SDL_SCANCODE_GRAVE = 53

Global Const $SDL_SCANCODE_COMMA = 54
Global Const $SDL_SCANCODE_PERIOD = 55
Global Const $SDL_SCANCODE_SLASH = 56

Global Const $SDL_SCANCODE_CAPSLOCK = 57

Global Const $SDL_SCANCODE_F1 = 58
Global Const $SDL_SCANCODE_F2 = 59
Global Const $SDL_SCANCODE_F3 = 60
Global Const $SDL_SCANCODE_F4 = 61
Global Const $SDL_SCANCODE_F5 = 62
Global Const $SDL_SCANCODE_F6 = 63
Global Const $SDL_SCANCODE_F7 = 64
Global Const $SDL_SCANCODE_F8 = 65
Global Const $SDL_SCANCODE_F9 = 66
Global Const $SDL_SCANCODE_F10 = 67
Global Const $SDL_SCANCODE_F11 = 68
Global Const $SDL_SCANCODE_F12 = 69

Global Const $SDL_SCANCODE_PRINTSCREEN = 70
Global Const $SDL_SCANCODE_SCROLLLOCK = 71
Global Const $SDL_SCANCODE_PAUSE = 72
Global Const $SDL_SCANCODE_INSERT = 73

Global Const $SDL_SCANCODE_HOME = 74
Global Const $SDL_SCANCODE_PAGEUP = 75
Global Const $SDL_SCANCODE_DELETE = 76
Global Const $SDL_SCANCODE_END = 77
Global Const $SDL_SCANCODE_PAGEDOWN = 78
Global Const $SDL_SCANCODE_RIGHT = 79
Global Const $SDL_SCANCODE_LEFT = 80
Global Const $SDL_SCANCODE_DOWN = 81
Global Const $SDL_SCANCODE_UP = 82

Global Const $SDL_SCANCODE_NUMLOCKCLEAR = 83

Global Const $SDL_SCANCODE_KP_DIVIDE = 84
Global Const $SDL_SCANCODE_KP_MULTIPLY = 85
Global Const $SDL_SCANCODE_KP_MINUS = 86
Global Const $SDL_SCANCODE_KP_PLUS = 87
Global Const $SDL_SCANCODE_KP_ENTER = 88
Global Const $SDL_SCANCODE_KP_1 = 89
Global Const $SDL_SCANCODE_KP_2 = 90
Global Const $SDL_SCANCODE_KP_3 = 91
Global Const $SDL_SCANCODE_KP_4 = 92
Global Const $SDL_SCANCODE_KP_5 = 93
Global Const $SDL_SCANCODE_KP_6 = 94
Global Const $SDL_SCANCODE_KP_7 = 95
Global Const $SDL_SCANCODE_KP_8 = 96
Global Const $SDL_SCANCODE_KP_9 = 97
Global Const $SDL_SCANCODE_KP_0 = 98
Global Const $SDL_SCANCODE_KP_PERIOD = 99

Global Const $SDL_SCANCODE_NONUSBACKSLASH = 100

Global Const $SDL_SCANCODE_APPLICATION = 101
Global Const $SDL_SCANCODE_POWER = 102

Global Const $SDL_SCANCODE_KP_EQUALS = 103
Global Const $SDL_SCANCODE_F13 = 104
Global Const $SDL_SCANCODE_F14 = 105
Global Const $SDL_SCANCODE_F15 = 106
Global Const $SDL_SCANCODE_F16 = 107
Global Const $SDL_SCANCODE_F17 = 108
Global Const $SDL_SCANCODE_F18 = 109
Global Const $SDL_SCANCODE_F19 = 110
Global Const $SDL_SCANCODE_F20 = 111
Global Const $SDL_SCANCODE_F21 = 112
Global Const $SDL_SCANCODE_F22 = 113
Global Const $SDL_SCANCODE_F23 = 114
Global Const $SDL_SCANCODE_F24 = 115
Global Const $SDL_SCANCODE_EXECUTE = 116
Global Const $SDL_SCANCODE_HELP = 117
Global Const $SDL_SCANCODE_MENU = 118
Global Const $SDL_SCANCODE_SELECT = 119
Global Const $SDL_SCANCODE_STOP = 120
Global Const $SDL_SCANCODE_AGAIN = 121
Global Const $SDL_SCANCODE_UNDO = 122
Global Const $SDL_SCANCODE_CUT = 123
Global Const $SDL_SCANCODE_COPY = 124
Global Const $SDL_SCANCODE_PASTE = 125
Global Const $SDL_SCANCODE_FIND = 126
Global Const $SDL_SCANCODE_MUTE = 127
Global Const $SDL_SCANCODE_VOLUMEUP = 128
Global Const $SDL_SCANCODE_VOLUMEDOWN = 129
Global Const $SDL_SCANCODE_LOCKINGCAPSLOCK = 130
Global Const $SDL_SCANCODE_LOCKINGNUMLOCK = 131
Global Const $SDL_SCANCODE_LOCKINGSCROLLLOCK = 132

Global Const $SDL_SCANCODE_KP_COMMA = 133
Global Const $SDL_SCANCODE_KP_EQUALS400 = 134

Global Const $SDL_SCANCODE_INTERNATIONAL = 135

Global Const $SDL_SCANCODE_INTERNATIONAL2 = 136
Global Const $SDL_SCANCODE_INTERNATIONAL3 = 137
Global Const $SDL_SCANCODE_INTERNATIONAL4 = 138
Global Const $SDL_SCANCODE_INTERNATIONAL5 = 139
Global Const $SDL_SCANCODE_INTERNATIONAL6 = 140
Global Const $SDL_SCANCODE_INTERNATIONAL7 = 141
Global Const $SDL_SCANCODE_INTERNATIONAL8 = 142
Global Const $SDL_SCANCODE_INTERNATIONAL9 = 143
Global Const $SDL_SCANCODE_LANG1 = 144
Global Const $SDL_SCANCODE_LANG2 = 145
Global Const $SDL_SCANCODE_LANG3 = 146
Global Const $SDL_SCANCODE_LANG4 = 147
Global Const $SDL_SCANCODE_LANG5 = 148
Global Const $SDL_SCANCODE_LANG6 = 149
Global Const $SDL_SCANCODE_LANG7 = 150
Global Const $SDL_SCANCODE_LANG8 = 151
Global Const $SDL_SCANCODE_LANG9 = 152

Global Const $SDL_SCANCODE_ALTERASE = 153
Global Const $SDL_SCANCODE_SYSREQ = 154
Global Const $SDL_SCANCODE_CANCEL = 155
Global Const $SDL_SCANCODE_CLEAR = 156
Global Const $SDL_SCANCODE_PRIOR = 157
Global Const $SDL_SCANCODE_RETURN2 = 158
Global Const $SDL_SCANCODE_SEPARATOR = 159
Global Const $SDL_SCANCODE_OUT = 160
Global Const $SDL_SCANCODE_OPER = 161
Global Const $SDL_SCANCODE_CLEARAGAIN = 162
Global Const $SDL_SCANCODE_CRSEL = 163
Global Const $SDL_SCANCODE_EXSEL = 164

Global Const $SDL_SCANCODE_KP_00 = 176
Global Const $SDL_SCANCODE_KP_000 = 177
Global Const $SDL_SCANCODE_THOUNSANDSSEPARATOR = 178
Global Const $SDL_SCANCODE_DECIMALSEPARATOR = 179
Global Const $SDL_SCANCODE_CURRENCYUINT = 180
Global Const $SDL_SCANCODE_CURRENCYSUBUINT = 181
Global Const $SDL_SCANCODE_KP_LEFTPAREN = 182
Global Const $SDL_SCANCODE_KP_RIGHTPAREN = 183
Global Const $SDL_SCANCODE_KP_LEFTBRACE = 184
Global Const $SDL_SCANCODE_KP_RIGHTBRACE = 185
Global Const $SDL_SCANCODE_KP_TAB = 186
Global Const $SDL_SCANCODE_KP_BACKSPACE = 187
Global Const $SDL_SCANCODE_KP_A = 188
Global Const $SDL_SCANCODE_KP_B = 189
Global Const $SDL_SCANCODE_KP_C = 190
Global Const $SDL_SCANCODE_KP_D = 191
Global Const $SDL_SCANCODE_KP_E = 192
Global Const $SDL_SCANCODE_KP_F = 193
Global Const $SDL_SCANCODE_KP_XOR = 194
Global Const $SDL_SCANCODE_KP_POWER = 195
Global Const $SDL_SCANCODE_KP_PERCENT = 196
Global Const $SDL_SCANCODE_KP_LESS = 197
Global Const $SDL_SCANCODE_KP_GREATER = 198
Global Const $SDL_SCANCODE_KP_AMPERSAND = 199
Global Const $SDL_SCANCODE_KP_DBLAMPERSAND = 200
Global Const $SDL_SCANCODE_KP_VERTICALBAR = 201
Global Const $SDL_SCANCODE_KP_DBLVERTICALBAR = 202
Global Const $SDL_SCANCODE_KP_COLON = 203
Global Const $SDL_SCANCODE_KP_HASH = 204
Global Const $SDL_SCANCODE_KP_SPACE = 205
Global Const $SDL_SCANCODE_KP_AT = 206
Global Const $SDL_SCANCODE_KP_EXCLAM = 207
Global Const $SDL_SCANCODE_KP_MEMSTORE = 208
Global Const $SDL_SCANCODE_KP_MEMRECALL = 209
Global Const $SDL_SCANCODE_KP_MEMCLEAR = 210
Global Const $SDL_SCANCODE_KP_MEMADD = 211
Global Const $SDL_SCANCODE_KP_MEMSUBTRACT = 212
Global Const $SDL_SCANCODE_KP_MEMULTIPLY = 213
Global Const $SDL_SCANCODE_KP_MEMDIVIDE = 214
Global Const $SDL_SCANCODE_KP_PLUSMINUS = 215
Global Const $SDL_SCANCODE_KP_CLEAR = 216
Global Const $SDL_SCANCODE_KP_CLEARENTRY = 217
Global Const $SDL_SCANCODE_KP_BINARY = 218
Global Const $SDL_SCANCODE_KP_OCTAL = 219
Global Const $SDL_SCANCODE_KP_DECIMAL = 220
Global Const $SDL_SCANCODE_KP_HEXADECIMAL = 221

Global Const $SDL_SCANCODE_LCTRL = 224
Global Const $SDL_SCANCODE_LSHIFT = 225
Global Const $SDL_SCANCODE_LALT = 226
Global Const $SDL_SCANCODE_LGUI = 227
Global Const $SDL_SCANCODE_RCTRL = 228
Global Const $SDL_SCANCODE_RSHIFT = 229
Global Const $SDL_SCANCODE_RALT = 230
Global Const $SDL_SCANCODE_RGUI = 231

Global Const $SDL_SCANCODE_MODE = 257

Global Const $SDL_SCANCODE_AUDIONEXT = 258
Global Const $SDL_SCANCODE_AUDIOPREV = 259
Global Const $SDL_SCANCODE_AUDIOSTOP = 260
Global Const $SDL_SCANCODE_AUDIOPLAY = 261
Global Const $SDL_SCANCODE_AUDIOMUTE = 262
Global Const $SDL_SCANCODE_MEDIASELECT = 263
Global Const $SDL_SCANCODE_WWW = 264
Global Const $SDL_SCANCODE_MAIL = 265
Global Const $SDL_SCANCODE_CALCULATOR = 266
Global Const $SDL_SCANCODE_COMPUTER = 267
Global Const $SDL_SCANCODE_AC_SEARCH = 268
Global Const $SDL_SCANCODE_AC_HOME = 269
Global Const $SDL_SCANCODE_AC_BACK = 270
Global Const $SDL_SCANCODE_AC_FORWARD = 271
Global Const $SDL_SCANCODE_AC_STOP = 272
Global Const $SDL_SCANCODE_AC_REFRESH = 273
Global Const $SDL_SCANCODE_AC_BOOKMARKS = 274

Global Const $SDL_SCANCODE_BRIGHTNESSDOWN = 275
Global Const $SDL_SCANCODE_BRIGHTNESSUP = 276
Global Const $SDL_SCANCODE_DISPLAYSWITCH = 277

Global Const $SDL_SCANCODE_KBDILLUMTOGGLE = 278
Global Const $SDL_SCANCODE_KBDILLUMDOWN = 279
Global Const $SDL_SCANCODE_KBDILLUMUP = 280
Global Const $SDL_SCANCODE_EJECT = 281
Global Const $SDL_SCANCODE_SLEEP = 282

Global Const $SDL_SCANCODE_APP1 = 283
Global Const $SDL_SCANCODE_APP2 = 284

Global Const $SDL_NUM_SCANCODES = 512

;Note dlecared as enum in the C code, but using consts here
Global Const $SDLK_UNKNOWN = 0
Global Const $SDLK_RETURN = 1
Global Const $SDLK_ESCAPE = 2
Global Const $SDLK_BACKSPACE = 3
Global Const $SDLK_TAB = 4
Global Const $SDLK_SPACE = 5
Global Const $SDLK_EXCLAIM = 6
Global Const $SDLK_QUOTEDEBL = 7
Global Const $SDLK_HASH = 8
Global Const $SDLK_PERCENT = 9
Global Const $SDLK_DOLLAR = 10
Global Const $SDLK_AMPERSAND = 11
Global Const $SDLK_QUOTE = 12
Global Const $SDLK_LEFTPAREN = 13
Global Const $SDLK_RIGHTPAREN = 14
Global Const $SDLK_ASTERISK = 15
Global Const $SDLK_PLUS = 16
Global Const $SDLK_COMMA = 17
Global Const $SDLK_MINUS = 18
Global Const $SDLK_PERIOD = 19
Global Const $SDLK_SLASH = 20
Global Const $SDLK_0 = 21
Global Const $SDLK_1 = 22
Global Const $SDLK_2 = 23
Global Const $SDLK_3 = 24
Global Const $SDLK_4 = 25
Global Const $SDLK_5 = 26
Global Const $SDLK_6 = 27
Global Const $SDLK_7 = 28
Global Const $SDLK_8 = 29
Global Const $SDLK_9 = 30
Global Const $SDLK_COLON = 31
Global Const $SDLK_SEMICOLON = 32
Global Const $SDLK_LESS = 33
Global Const $SDLK_EQUALS = 34
Global Const $SDLK_GREATER = 35
Global Const $SDLK_QUESTION = 36
Global Const $SDLK_AT = 37
Global Const $SDLK_LEFTBRACKET = 38
Global Const $SDLK_BACKSLASH = 39
Global Const $SDLK_RIGHTBRACKET = 40
Global Const $SDLK_CARET = 41
Global Const $SDLK_UNDERSCORE = 42
Global Const $SDLK_BACKQUOTE = 43
Global Const $SDLK_a = 44
Global Const $SDLK_b = 45
Global Const $SDLK_c = 46
Global Const $SDLK_d = 47
Global Const $SDLK_e = 48
Global Const $SDLK_f = 49
Global Const $SDLK_g = 50
Global Const $SDLK_h = 51
Global Const $SDLK_i = 52
Global Const $SDLK_j = 53
Global Const $SDLK_k = 54
Global Const $SDLK_l = 55
Global Const $SDLK_m = 56
Global Const $SDLK_n = 57
Global Const $SDLK_o = 58
Global Const $SDLK_p = 59
Global Const $SDLK_q = 60
Global Const $SDLK_r = 61
Global Const $SDLK_s = 62
Global Const $SDLK_t = 63
Global Const $SDLK_u = 64
Global Const $SDLK_v = 65
Global Const $SDLK_w = 66
Global Const $SDLK_x = 67
Global Const $SDLK_y = 68
Global Const $SDLK_z = 69

Global Const $SDLK_CAPSLOCK = $SDL_SCANCODE_CAPSLOCK

Global Const $SDLK_F1 = $SDL_SCANCODE_F1
Global Const $SDLK_F2 = $SDL_SCANCODE_F2
Global Const $SDLK_F3 = $SDL_SCANCODE_F3
Global Const $SDLK_F4 = $SDL_SCANCODE_F4
Global Const $SDLK_F5 = $SDL_SCANCODE_F5
Global Const $SDLK_F6 = $SDL_SCANCODE_F6
Global Const $SDLK_F7 = $SDL_SCANCODE_F7
Global Const $SDLK_F8 = $SDL_SCANCODE_F8
Global Const $SDLK_F9 = $SDL_SCANCODE_F9
Global Const $SDLK_F10 = $SDL_SCANCODE_F10
Global Const $SDLK_F11 = $SDL_SCANCODE_F11
Global Const $SDLK_F12 = $SDL_SCANCODE_F12

Global Const $SDLK_PRINTSCREEN = $SDL_SCANCODE_PRINTSCREEN
Global Const $SDLK_SCROLLLOCK = $SDL_SCANCODE_SCROLLLOCK
Global Const $SDLK_PAUSE = $SDL_SCANCODE_PAUSE
Global Const $SDLK_INSERT = $SDL_SCANCODE_INSERT
Global Const $SDLK_HOME = $SDL_SCANCODE_HOME
Global Const $SDLK_PAGEUP = $SDL_SCANCODE_PAGEUP
Global Const $SDLK_DELETE = $SDL_SCANCODE_DELETE
Global Const $SDLK_END = $SDL_SCANCODE_END
Global Const $SDLK_PAGEDOWN = $SDL_SCANCODE_PAGEDOWN
Global Const $SDLK_RIGHT = $SDL_SCANCODE_RIGHT
Global Const $SDLK_LEFT = $SDL_SCANCODE_LEFT
Global Const $SDLK_DOWN = $SDL_SCANCODE_DOWN
Global Const $SDLK_UP = $SDL_SCANCODE_UP

Global Const $SDLK_NUMLOCKCLEAR = $SDL_SCANCODE_NUMLOCKCLEAR
Global Const $SDLK_KP_DIVIDE = $SDL_SCANCODE_KP_DIVIDE
Global Const $SDLK_KP_MULTIPLY = $SDL_SCANCODE_KP_MULTIPLY
Global Const $SDLK_KP_MINUS = $SDL_SCANCODE_KP_MINUS
Global Const $SDLK_KP_PLUS = $SDL_SCANCODE_KP_PLUS
Global Const $SDLK_KP_ENTER = $SDL_SCANCODE_KP_ENTER
Global Const $SDLK_KP_1 = $SDL_SCANCODE_KP_1
Global Const $SDLK_KP_2 = $SDL_SCANCODE_KP_2
Global Const $SDLK_KP_3 = $SDL_SCANCODE_KP_3
Global Const $SDLK_KP_4 = $SDL_SCANCODE_KP_4
Global Const $SDLK_KP_5 = $SDL_SCANCODE_KP_5
Global Const $SDLK_KP_6 = $SDL_SCANCODE_KP_6
Global Const $SDLK_KP_7 = $SDL_SCANCODE_KP_7
Global Const $SDLK_KP_8 = $SDL_SCANCODE_KP_8
Global Const $SDLK_KP_9 = $SDL_SCANCODE_KP_9
Global Const $SDLK_KP_0 = $SDL_SCANCODE_KP_0
Global Const $SDLK_KP_PERIOD = $SDL_SCANCODE_KP_PERIOD

Global Const $SDLK_APPLICATION = $SDL_SCANCODE_APPLICATION
Global Const $SDLK_POWER = $SDL_SCANCODE_POWER
;Global Const $SDLK_EQUALS = $SDL_SCANCODE_EQUALS ;Redeclaration?
Global Const $SDLK_F13 = $SDL_SCANCODE_F13
Global Const $SDLK_F14 = $SDL_SCANCODE_F14
Global Const $SDLK_F15 = $SDL_SCANCODE_F15
Global Const $SDLK_F16 = $SDL_SCANCODE_F16
Global Const $SDLK_F17 = $SDL_SCANCODE_F17
Global Const $SDLK_F18 = $SDL_SCANCODE_F18
Global Const $SDLK_F19 = $SDL_SCANCODE_F19
Global Const $SDLK_F20 = $SDL_SCANCODE_F20
Global Const $SDLK_F21 = $SDL_SCANCODE_F21
Global Const $SDLK_F22 = $SDL_SCANCODE_F22
Global Const $SDLK_F23 = $SDL_SCANCODE_F23
Global Const $SDLK_F24 = $SDL_SCANCODE_F24
Global Const $SDLK_EXECUTE = $SDL_SCANCODE_EXECUTE
Global Const $SDLK_HELP = $SDL_SCANCODE_HELP
Global Const $SDLK_MENU = $SDL_SCANCODE_MENU
Global Const $SDLK_SELECT = $SDL_SCANCODE_SELECT
Global Const $SDLK_STOP = $SDL_SCANCODE_STOP
Global Const $SDLK_AGAIN = $SDL_SCANCODE_AGAIN
Global Const $SDLK_UNDO = $SDL_SCANCODE_UNDO
Global Const $SDLK_CUT = $SDL_SCANCODE_CUT
Global Const $SDLK_COPY = $SDL_SCANCODE_COPY
Global Const $SDLK_PASTE = $SDL_SCANCODE_PASTE
Global Const $SDLK_FIND = $SDL_SCANCODE_FIND
Global Const $SDLK_MUTE = $SDL_SCANCODE_MUTE
Global Const $SDLK_VOLUMEUP = $SDL_SCANCODE_VOLUMEUP
Global Const $SDLK_VOLUMEDOWN = $SDL_SCANCODE_VOLUMEDOWN
Global Const $SDLK_KP_COMMA = $SDL_SCANCODE_KP_COMMA
Global Const $SDLK_KP_EQUALS400 = $SDL_SCANCODE_KP_EQUALS400

Global Const $SDLK_ALTERASE = $SDL_SCANCODE_ALTERASE
Global Const $SDLK_SYSREQ = $SDL_SCANCODE_SYSREQ
Global Const $SDLK_CANCEL = $SDL_SCANCODE_CANCEL
Global Const $SDLK_CLEAR = $SDL_SCANCODE_CLEAR
Global Const $SDLK_PRIOR = $SDL_SCANCODE_PRIOR
Global Const $SDLK_RETURN2 = $SDL_SCANCODE_RETURN2
Global Const $SDLK_SEPARATOR = $SDL_SCANCODE_SEPARATOR
Global Const $SDLK_OUT = $SDL_SCANCODE_OUT
Global Const $SDLK_OPER = $SDL_SCANCODE_OPER
Global Const $SDLK_CLEARAGAIN = $SDL_SCANCODE_CLEARAGAIN
Global Const $SDLK_CRSEL = $SDL_SCANCODE_CRSEL
Global Const $SDLK_EXSEL = $SDL_SCANCODE_EXSEL

Global Const $SDLK_KP_00 = $SDL_SCANCODE_KP_00
Global Const $SDLK_KP_000 = $SDL_SCANCODE_KP_000
Global Const $SDLK_THOUNSANDSSEPARATOR = $SDL_SCANCODE_THOUNSANDSSEPARATOR
Global Const $SDLK_DECIMALSEPARATOR = $SDL_SCANCODE_DECIMALSEPARATOR
Global Const $SDLK_CURRENCYUINT = $SDL_SCANCODE_CURRENCYUINT
Global Const $SDLK_CURRENCYSUBUNIT = $SDL_SCANCODE_CURRENCYSUBUINT
Global Const $SDLK_KP_LEFTPAREN = $SDL_SCANCODE_KP_LEFTPAREN
Global Const $SDLK_KP_LEFTBRACE = $SDL_SCANCODE_KP_LEFTBRACE
Global Const $SDLK_KP_RIGHTPAREN = $SDL_SCANCODE_KP_RIGHTPAREN
Global Const $SDLK_KP_RIGHTBRACE = $SDL_SCANCODE_KP_RIGHTBRACE
Global Const $SDLK_KP_TAB = $SDL_SCANCODE_KP_TAB
Global Const $SDLK_KP_BACKSPACE = $SDL_SCANCODE_KP_BACKSPACE
Global Const $SDLK_KP_A = $SDL_SCANCODE_KP_A
Global Const $SDLK_KP_B = $SDL_SCANCODE_KP_B
Global Const $SDLK_KP_C = $SDL_SCANCODE_KP_C
Global Const $SDLK_KP_D = $SDL_SCANCODE_KP_D
Global Const $SDLK_KP_E = $SDL_SCANCODE_KP_E
Global Const $SDLK_KP_F = $SDL_SCANCODE_KP_F
Global Const $SDLK_KP_XOR = $SDL_SCANCODE_KP_XOR
Global Const $SDLK_KP_POWER = $SDL_SCANCODE_KP_POWER
Global Const $SDLK_KP_PERCENT = $SDL_SCANCODE_KP_PERCENT
Global Const $SDLK_KP_LESS = $SDL_SCANCODE_KP_LESS
Global Const $SDLK_KP_GREATER = $SDL_SCANCODE_KP_GREATER
Global Const $SDLK_KP_AMPERSAND = $SDL_SCANCODE_KP_AMPERSAND
Global Const $SDLK_KP_DBLAMPERSAND = $SDL_SCANCODE_KP_DBLAMPERSAND
Global Const $SDLK_KP_VERTICALBAR = $SDL_SCANCODE_KP_VERTICALBAR
Global Const $SDLK_KP_DBLVERTICALBAR = $SDL_SCANCODE_KP_DBLVERTICALBAR
Global Const $SDLK_KP_COLON = $SDL_SCANCODE_KP_COLON
Global Const $SDLK_KP_HASH = $SDL_SCANCODE_KP_HASH
Global Const $SDLK_KP_SPACE = $SDL_SCANCODE_KP_SPACE
Global Const $SDLK_KP_AT = $SDL_SCANCODE_KP_AT
Global Const $SDLK_KP_EXCLAM = $SDL_SCANCODE_KP_EXCLAM
Global Const $SDLK_KP_MEMSTORE = $SDL_SCANCODE_KP_MEMSTORE
Global Const $SDLK_KP_MEMRECALL = $SDL_SCANCODE_KP_MEMRECALL
Global Const $SDLK_KP_MEMCLEAR = $SDL_SCANCODE_KP_MEMCLEAR
Global Const $SDLK_KP_MEMADD = $SDL_SCANCODE_KP_MEMADD
Global Const $SDLK_KP_MEMSUBSTRACT = $SDL_SCANCODE_KP_MEMSUBTRACT
Global Const $SDLK_KP_MEMMULTIPLY = $SDL_SCANCODE_KP_MEMULTIPLY
Global Const $SDLK_KP_MEMDIVIDE = $SDL_SCANCODE_KP_MEMDIVIDE
Global Const $SDLK_KP_PLUSMINUS = $SDL_SCANCODE_KP_PLUSMINUS
Global Const $SDLK_KP_CLEAR = $SDL_SCANCODE_KP_CLEAR
Global Const $SDLK_KP_CLEARENTRY = $SDL_SCANCODE_KP_CLEARENTRY
Global Const $SDLK_KP_BINARY = $SDL_SCANCODE_KP_BINARY
Global Const $SDLK_KP_OCTAL = $SDL_SCANCODE_KP_OCTAL
Global Const $SDLK_KP_DECIMAL = $SDL_SCANCODE_KP_DECIMAL
Global Const $SDLK_KP_HEXADECIMAL = $SDL_SCANCODE_KP_HEXADECIMAL

Global Const $SDLK_LCTRL = $SDL_SCANCODE_LCTRL
Global Const $SDLK_LSHFIT = $SDL_SCANCODE_LSHIFT
Global Const $SDLK_LALT = $SDL_SCANCODE_LALT
Global Const $SDLK_LGUI = $SDL_SCANCODE_LGUI
Global Const $SDLK_RCTRL = $SDL_SCANCODE_RCTRL
Global Const $SDLK_RSHIFT = $SDL_SCANCODE_RSHIFT
Global Const $SDLK_RALT = $SDL_SCANCODE_RALT
Global Const $SDLK_RGUI = $SDL_SCANCODE_RGUI

Global Const $SDLK_MODE = $SDL_SCANCODE_MODE

Global Const $SDLK_AUDIONEXT = $SDL_SCANCODE_AUDIONEXT
Global Const $SDLK_AUDIOPREV = $SDL_SCANCODE_AUDIOPREV
Global Const $SDLK_AUDIOSTOP = $SDL_SCANCODE_AUDIOSTOP
Global Const $SDLK_AUDIOPLAY = $SDL_SCANCODE_AUDIOPLAY
Global Const $SDLK_AUDIOMUTE = $SDL_SCANCODE_AUDIOMUTE
Global Const $SDLK_MEDIASELECT = $SDL_SCANCODE_MEDIASELECT
Global Const $SDLK_WWW = $SDL_SCANCODE_WWW
Global Const $SDLK_MAIL = $SDL_SCANCODE_MAIL
Global Const $SDLK_CALCULATOR = $SDL_SCANCODE_CALCULATOR
Global Const $SDLK_COMPUTER = $SDL_SCANCODE_COMPUTER
Global Const $SDLK_AC_SEARCH = $SDL_SCANCODE_AC_SEARCH
Global Const $SDLK_AC_HOME = $SDL_SCANCODE_AC_HOME
Global Const $SDLK_AC_FORWARD = $SDL_SCANCODE_AC_FORWARD
Global Const $SDLK_AC_STOP = $SDL_SCANCODE_AC_STOP
Global Const $SDLK_AC_REFRESH = $SDL_SCANCODE_AC_REFRESH
Global Const $SDLK_AC_BOOKMARKS = $SDL_SCANCODE_AC_BOOKMARKS

Global Const $SDLK_BRIGHTNESSDOWN = $SDL_SCANCODE_BRIGHTNESSDOWN
Global Const $SDLK_BRIGHTNESSUP = $SDL_SCANCODE_BRIGHTNESSUP
Global Const $SDLK_DISPLAYSWITCH = $SDL_SCANCODE_DISPLAYSWITCH
Global Const $SDLK_KBDILLUMTOGGLE = $SDL_SCANCODE_KBDILLUMTOGGLE
Global Const $SDLK_KBDILLUMDOWN = $SDL_SCANCODE_KBDILLUMDOWN
Global Const $SDLK_KBDILLUMUP = $SDL_SCANCODE_KBDILLUMUP
Global Const $SDLK_EJECT = $SDL_SCANCODE_EJECT
Global Const $SDLK_SLEEP = $SDL_SCANCODE_SLEEP

Global Const $KMOD_NONE = 0
Global Const $KMOD_LSHIFT = 1
Global Const $KMOD_RSHIFT = 2
Global Const $KMOD_LCTRL = 64
Global const $KMOD_RCTRL = 128
Global Const $KMOD_LALT = 256
Global Const $KMOD_RALT = 512
Global Const $KMOD_LGUI = 1024
Global Const $KMOD_RGUI = 2048
Global Const $KMOD_NUMS = 4096
Global Const $KMOD_CAPS = 8192
Global Const $KMOD_MODE = 16384
Global Const $KMOD_RESERVED = 32768

Global Const $KMOD_CTRL = BitOR($KMOD_LCTRL,$KMOD_RCTRL)
Global Const $KMOD_SHIFT = BitOR($KMOD_LSHIFT,$KMOD_RSHIFT)
Global Const $KMOD_ALT = BitOR($KMOD_LALT,$KMOD_RALT)
Global Const $KMOD_GUI = BitOR($KMOD_LGUI,$KMOD_RGUI)

;WindowShape Flags
Global Const $SDL_NONSHAPEABLE_WINDOW = -1
Global Const $SDL_INVALID_SHAPE_ARGUMENT = -2
Global Const $SDL_WINDOW_LACKS_SHAPE = -3

Global Const $SHAPE_MODE_FAULT = 0
Global Const $SHAPE_MODE_BINARIZE_ALPHA = 1
Global Const $SHAPE_MODE_REVERSE_BINARIZE_ALPHA = 2
Global Const $SHAPE_MODE_COLOR_KEY = 3

;Misc flags
Global Const $SDL_FALSE = 0
Global Const $SDL_TRUE = 1

Global Const $DUMMY_ENUM_VALUE = 0

Global Const $SDL_SWSURFACE = 0
Global Const $SDL_PREALLOC = 1
Global Const $SDL_RLEACCEL = 2
Global Const $SDL_DONTFREE = 4

Global Const $SDL_MUSTLOCK = $SDL_RLEACCEL

Global Enum $SDL_WINRT_PATH_INSTALLED_LOCATON, $SDL_WINRT_PATH_LOCAL_FOLDER, $SDL_WINRT_PATH_ROAMING_FOLDER, $SDL_WINRT_PATH_TEMP_FOLDER

Global Enum $SDL_SYSWM_UNKNOWN, $SDL_SYSWM_WINDOWS, $SDL_SYSWM_X11, $SDL_SYSWM_DIRECTFB, $SDL_SYSWM_COCOA, $SDL_SYSWM_UIKIT, $SDL_SYSWM_WAYLAND, $SDL_SYSWM_MIR, $SDL_SYSWM_WINRT

Global Const $SDLTEST_MAX_LOGMESSAGE_LENGTH = 3584

Global Const $ASSERT_FAIL = 0
Global Const $ASSERT_PASS = 1

Global Const $DEFAULT_WINDOW_WIDTH = 640
Global Const $DEFAULT_WINDOW_HEIGHT = 480

Global Const $VERBOSE_VIDEO = 1
Global Const $VERBOSE_MODES = 2
Global Const $VERBOSE_RENDER = 4
Global Const $VERBOSE_EVENT = 8
Global Const $VERBOSE_AUDIO = 16

Global Const $FONT_CHARACTER_SIZE = 8

Global Const $TEST_ENABLED = 1
Global Const $TEST_DISABLED = 0

Global Const $TEST_ABORTED = -1
Global Const $TEST_STARTED = 0
Global Const $TEST_COMPLETED = 1
Global Const $TEST_SKIPPED = 2

Global Const $TEST_RESULT_PASSED = 0
Global Const $TEST_RESULT_FAILED = 1
Global Const $TEST_RESULT_NO_ASSERT = 2
Global Const $TEST_RESULT_SKIPPED = 3
Global Const $TEST_RESULT_SETUP_FAILURE = 4

Global Enum $SDL_THREAD_PRIORITY_LOW, $SDL_THREAD_PRIORITY_NORMAL, $SDL_THREAD_PRIORITY_HIGH

Global Const $SDL_TOUCH_MOUSEID = -1

;SDL version flags
Global Const $SDL_MAJOR_VERSION = 2
Global Const $SDL_MINOR_VERSION = 0
Global Const $SDL_PATCHLEVEL = 8

;Window flags Cont.
Global Const $SDL_WINDOWPOS_UNDEFINED_MASK = 536805376
Global Const $SDL_WINDOWPOS_UNDEFINED_DISPLAY = $SDL_WINDOWPOS_UNDEFINED_MASK
Global Const $SDL_WINDOWPOS_UNDEFINED = $SDL_WINDOWPOS_UNDEFINED_DISPLAY
Global Const $SDL_WINDOWPOS_ISUNDEFINED = $SDL_WINDOWPOS_UNDEFINED_MASK

Global Const $SDL_WINDOWPOS_CENTERED_MASK = 805240832
Global Const $SDL_WINDOWPOS_CENTERED_DISPLAY = $SDL_WINDOWPOS_CENTERED_MASK
Global Const $SDL_WINDOWPOS_CENTERED = $SDL_WINDOWPOS_CENTERED_DISPLAY
Global Const $SDL_WINDOWPOS_ISCENTERED = $SDL_WINDOWPOS_CENTERED_MASK

;WindowEvent flags
Global Const $SDL_WINDOWEVENT_NONE = 0
Global Const $SDL_WINDOWEVENT_SHOWN = 1
Global Const $SDL_WINDOWEVENT_HIDDEN = 2
Global Const $SDL_WINDOWEVENT_EXPOSED = 3

Global Const $SDL_WINDOWEVENT_MOVED = 4

Global Const $SDL_WINDOWEVENT_RESIZED = 5
Global Const $SDL_WINDOWEVENT_SIZE_CHANGED = 6
Global Const $SDL_WINDOWEVENT_MINIMIZED = 7
Global Const $SDL_WINDOWEVENT_MAXIMIZED = 8
Global Const $SDL_WINDOWEVENT_RESTORED = 9

Global Const $SDL_WINDOWEVENT_ENTER = 10
Global Const $SDL_WINDOWEVENT_LEAVE = 11
Global Const $SDL_WINDOWEVENT_FOCUS_GAINED = 12
Global Const $SDL_WINDOWEVENT_FOCUS_LOST = 13
Global Const $SDL_WINDOWEVENT_CLOSE = 14

;GL flags
Global Const $SDL_GL_RED_SIZE = 0
Global Const $SDL_GL_GREEN_SIZE = 1
Global Const $SDL_GL_BLUE_SIZE = 2
Global Const $SDL_GL_ALPHA_SIZE = 3
Global Const $SDL_GL_BUFFER_SIZE = 4
Global Const $SDL_GL_DOUBLEBUFFER = 5
Global Const $SDL_GL_DEPTH_SIZE = 6
Global Const $SDL_GL_STENCIL_SIZE = 7
Global Const $SDL_GL_ACCUM_RED_SIZE = 8
Global Const $SDL_GL_ACCUM_GREEN_SIZE = 9
Global Const $SDL_GL_ACCUM_BLUE_SIZE = 10
Global Const $SDL_GL_ACCUM_ALPHA_SIZE = 11
Global Const $SDL_GL_STEREO = 12
Global Const $SDL_GL_MULTISAMPLEBUFFERS = 13
Global Const $SDL_GL_MULTISAMPLESAMPLES = 14
Global Const $SDL_GL_ACCELERATED_VISUAL = 15
Global Const $SDL_GL_RETAINED_BACKING = 16
Global Const $SDL_GL_CONTEXT_MAJOR_VERSION = 17
Global Const $SDL_GL_CONTEXT_MINOR_VERSION = 18
Global Const $SDL_GL_CONTEXT_EGL = 19
Global Const $SDL_GL_CONTEXT_FLAGS = 20
Global Const $SDL_GL_CONTEXT_PROFILE_MASK = 21
Global Const $SDL_GL_SHARE_WITH_CURRENT_CONTEXT = 22
Global Const $SDL_GL_FRAMEBUFFER_SRGB_CAPABLE = 23

;gl profile flags
Global Const $SDL_GL_CONTEXT_PROFILE_CORE = 1
Global Const $SDL_GL_CONTEXT_PROFILE_COMPATIBILITY = 2
Global Const $SDL_GL_CONTEXT_PROFILE_ES = 4

Global Const $SDL_GL_CONTEXT_DEBUG_FLAG = 1
Global Const $SDL_GL_CONTEXT_FORWARD_COMPATIBLE_FLAG = 2
Global Const $SDL_GL_CONTEXT_ROBUST_ACCESS_FLAG = 4
Global Const $SDL_GL_CONTEXT_RESET_ISOLATION_FLAG = 8

;SDL RWOPs flags
Global Const $SDL_RWOPS_UNKNOWN = 0
Global Const $SDL_RWOPS_WINFILE = 1
Global Const $SDL_RWOPS_STDFILE = 2
Global Const $SDL_RWOPS_JNIFILE = 3
Global Const $SDL_RWOPS_MEMORY = 4
Global Const $SDL_RWOPS_MEMORY_RO = 5

Global Const $RW_SEEK_SET = 0
Global Const $RW_SEEK_CUR = 1
Global Const $RW_SEEK_END = 2

;Render flags
Global Const $SDL_RENDERER_SOFTWARE = 1
Global Const $SDL_RENDERER_ACCELERATED = 2
Global Const $SDL_RENDERER_PRESENTVSYNC = 4
Global Const $SDL_RENDERER_TARGETEXTURE = 8

Global Const $SDL_TEXTUREACCESS_STATIC = 0
Global Const $SDL_TEXTUREACESS_STREAMING = 1
Global Const $SDL_TEXTUREACESS_TARGET = 2

Global Const $SDL_TEXTUREMODULATE_NONE = 0
Global Const $SDL_TEXTUREMODULATE_COLOR = 1
Global Const $SDL_TEXTUREMODULATE_ALPHA = 2

Global Enum $SDL_FLIP_NONE, $SDL_FLIP_HORIZONTAL, $SDL_FLIP_VERTICAL

Global Enum $SDL_PIXELTYPE_UNKNOWN, $SDL_PIXELTYPE_INDEX1, $SDL_PIXELTYPE_INDEX4,$SDL_PIXELTYPE_INDEX8,$SDL_PIXELTYPE_PACKED8,$SDL_PIXELTYPE_PACKED16,$SDL_PIXELTYPE_PACKED32,$SDL_PIXELTYPE_ARRAYU8,$SDL_PIXELTYPE_ARRAYU16,$SDL_PIXELTYPE_ARRAYU32, $SDL_PIXELTYPE_ARRAYF16,$SDL_PIXELTYPE_ARRAYF32

Global Enum $SDL_BITMAPORDER_NONE, $SDL_BITMAPORDER_4321, $SDL_BITMAPORDER_1234

Global Enum $SDL_PACKEDORDER_NONE,$SDL_PACKEDORDER_XRGB,$SDL_PACKEDORDER_RGBX,$SDL_PACKEDORDER_ARGB,$SDL_PACKEDORDER_RGBA,$SDL_PACKEDORDER_XBGR,$SDL_PACKEDORDER_BGRX,$SDL_PACKEDORDER_ABGR,$SDL_PACKEDORDER_BGRA

Global Enum $SDL_ARRAYORDER_NONE,$SDL_ARRAYORDER_RGB,$SDL_ARRAYORDER_RGBA,$SDL_ARRAYORDER_ARGB,$SDL_ARRAYORDER_BGR,$SDL_ARRAYORDER_BGRA,$SDL_ARRAYORDER_ABGR

Global Enum $SDL_PACKEDLAYOUT_NONE,$SDL_PACKEDLAYOUT_332,$SDL_PACKEDLAYOUT_4444,$SDL_PACKEDLAYOUT_1555,$SDL_PACKEDLAYOUT_5551,$SDL_PACKEDLAYOUT_565,$SDL_PACKEDLAYOUT_8888,$SDL_PACKEDLAYOUT_2101010,$SDL_PACKEDLAYOUT_1010102

Global Enum $SDL_POWERSTATE_UNKNOWN,$SDL_POWERSTATE_ON_BATTERY,$SDL_POWERSTATE_NO_BATTERY,$SDL_POWERSTATE_CHARGING,$SDL_POWERSTATE_CHARGED

Global Enum $SDL_JOYSTICK_TYPE_UNKNOWN,$SDL_JOYSTICK_TYPE_GAMECONTROLLER,$SDL_JOYSTICK_TYPE_WHEEL,$SDL_JOYSTICK_TYPE_ARCADE_STICK,$SDL_JOYSTICK_TYPE_FLIGHT_STICK,$SDL_JOYSTICK_TYPE_DANCE_PAD,$SDL_JOYSTICK_TYPE_GUITAR,$SDL_JOYSTICK_DRUM_KIT,$SDL_JOYSTICK_ARCADE_PAD,$SDL_JOYSTICK_TYPE_THROTTLE

Global Enum $SDL_JOYSTICK_POWER_UNKNOWN = -1,$SDL_JOYSTICK_POWER_EMPTY,$SDL_JOYSTICK_POWER_LOW,$SDL_JOYSTICK_POWER_MEDIUM,$SDL_JOYSTICK_POWER_FULL,$SDL_JOYSTICK_POWER_WIRED,$SDL_JOYSTICK_POWER_MAX

;Open the SDL2 DLL
Global $SDL = ("SDL2.dll")

;Check to make sure SDL2 DLL is there
if $SDL = -1 Then
   MsgBox($MB_SYSTEMMODAL,"Error","Could not load SDL2.dll!\n")
EndIf

;Struct for SDL_RECT
Func SDL_Rect($x,$y,$w,$h)
   $xSDL_Rect = DllStructCreate("int;int;int;int")
   DllStructSetData($SDL_Rect,1,$x)
   DllStructSetData($SDL_Rect,2,$y)
   DllStructSetData($SDL_Rect,3,$w)
   DllStructSetData($SDL_Rect,4,$h)
   Return $xSDL_Rect
EndFunc

;SDL Init Functions
Func SDL_Init($flags)
   Local $xSDL_Init = DllCall($SDL,"uint:cdecl","SDL_Init","uint", $flags)
   Return $xSDL_Init[0]
EndFunc

Func SDL_InitSubSystem($flags)
  Local $xSDL_InitSubSystem = DllCall($SDL,"int:cdecl","SDL_InitSubSystem","uint", $flags)
   Return $xSDL_InitSubSystem[0]
EndFunc

Func SDL_Quit()
   $xSDL_Quit = DllCall($SDL,"none","SDL_Quit")
   DllClose($SDL)
EndFunc

Func SDL_QuitSubSystem($flags)
   $xSDL_QuitSubSystem = DllCall($SDL,"none","SDL_QuitSubSystem","uint",$flags)
EndFunc

Func SDL_SetMainReady()
   $xSDL_SetMainReady = DllCall($SDL,"none","SDL_SetMainReady","")
EndFunc

Func SDL_WasInit($flags)
   Local $xSDL_WasInit = DllCall($SDL,"uint:cdecl","SDL_WasInit","uint",$flags)
   Return $xSDL_WasInit[0]
EndFunc

Func SDL_WinRTRunApp($f,$r)
   Local $xSDL_WinRTRunApp = DllCall($SDL,"int:cdecl","SDL_WinRTRunApp","ptr",$f,"ptr",$r)
   Return $xSDL_WinRTRunApp[0]
EndFunc

;SDL Config Funcs

;SDL Window Funcs
Func SDL_CreateWindow($title,$x,$y,$w,$h,$flags)
   Local $xSDL_CreateWindow = DllCall($SDL,"ptr:cdecl","SDL_CreateWindow","ptr",$title,"int",$x,"int",$y,"int",$w,"int",$h,"uint",$flags)
   Return $xSDL_CreateWindow[0]
EndFunc

Func SDL_CreateWindowAndRenderer($w,$h,$flags,$win,$ren)
   Local $xSDL_CreateWindowAndRenderer = DllCall($SDL,"int:cdecl","SDL_CreateWindowAndRenderer","int",$w,"int",$h,"uint",$flags,"ptr",$win,"ptr",$ren)
   Return $xSDL_CreateWindowAndRenderer[0]
EndFunc

Func SDL_CreateWindowFrom($data)
   Local $xSDL_CreateWindowFrom = DllCall($SDL,"ptr:cdecl","SDL_CreateWindowFrom","ptr",$data)
   Return $xSDL_CreateWindowFrom[0]
EndFunc

Func SDL_DestroyWindow($win)
   $xSDL_DestroyWindow = DllCall($SDL,"none","SDL_DestroyWindow","ptr",$win)
   Return $xSDL_DestroyWindow[0]
EndFunc

Func SDL_DisableScreenSaver()
   $xSDL_DisableScreenSaver = DllCall($SDL,"none","SDL_DisableScreenSaver")
EndFunc

Func SDL_EnableScreenSaver()
   $xSDL_EnableScreenSaver = DllCall($SDL,"none","SDL_EnableScreenSaver")
EndFunc

Func SDL_GL_CreateContext($win)
  Local $xSDL_GL_CreateContext = DllCall($SDL,"ptr:cdecl","SDL_GL_CreateContext","ptr",$win)
   Return $xSDL_GL_CreateContext[0]
EndFunc

Func SDL_GL_DeleteContext($context)
   $xSDL_GL_DeleteContext = DllCall($SDL,"none","SDL_GL_DeleteContext","ptr",$context)
   Return $xSDL_GL_DeleteContext[0]
EndFunc

Func SDL_GL_ExtensionSupported($extension)
   Local $xSDL_GL_ExtensionSupported = DllCall($SDL,"bool:cdecl","SDL_GL_ExtensionSupported","ptr",$extension)
   Return $xSDL_GL_ExtensionSupported[0]
EndFunc

Func SDL_GL_GetAttribute($attr,$value)
   Local $xSDL_GL_GetAttribute = DllCall($SDL,"int:cdecl","SDL_GL_GetAttribute","ptr",$attr,"int",$value)
   Return $xSDL_GL_GetAttribute[0]
EndFunc

Func SDL_GL_GetCurrentContext()
   Local $xSDL_GL_GetCurrentContext = DllCall($SDL,"ptr:cdecl","SDL_GL_GetCurrentContext")
   Return $xSDL_GL_GetCurrentContext[0]
EndFunc

Func SDL_GL_GetCurrentWindow()
   Local $xSDL_GL_GetCurrentWindow = DllCall($SDL,"ptr:cdecl","SDL_GL_GetCurrentWindow"
   Return $xSDL_GL_GetCurrentWindow[0]
EndFunc

Func SDL_GL_GetDrawableSize($win,$w,$h)
   Local $xSDL_GL_GetDrawableSize = DllCall($SDL,"none","SDL_GL_GetDrawableSize","ptr",$win,"ptr",$w,"ptr",$h)
   Return $xSDL_GL_GetDrawableSize[0]
EndFunc

Func SDL_GL_GetProcAddress($proc)
  Local $xSDL_GL_GetProcAddress = DllCall($SDL,"ptr:cdecl","SDL_GL_GetProcAddress","ptr",$proc)
   Return $xSDL_GL_GetProcAddress[0]
EndFunc

Func SDL_GL_GetSwapInterval()
   Local $xSDL_GL_GetSwapInterval = DllCall($SDL,"int:cdecl","SDL_GL_GetSwapInterval")
   Return $xSDL_GL_GetSwapInterval[0]
EndFunc

Func SDL_GL_LoadLibrary($path)
   Local $xSDL_GL_LoadLibrary = DllCall($SDL,"int:cdecl","SDL_GL_LoadLibrary","ptr",$path)
   Return $xSDL_GL_LoadLibrary[0]
EndFunc

Func SDL_GL_MakeCurrent($win,$context)
   Local $xSDL_GL_MakeCurrent = DllCall($SDL,"int:cdecl","SDL_GL_MakeCurrent","ptr",$win,"ptr",$context)
   Return $xSDL_GL_MakeCurrent[0]
EndFunc

Func SDL_GL_ResetAttributes()
   $xSDL_GL_ResetAttributes = DllCall($SDL,"none","SDL_GL_ResetAttributes")
   Return $xSDL_GL_ResetAttributes[0]
EndFunc

Func SDL_GL_SetAttribute($attr,$value)
   Local $xSDL_GL_SetAttribute = DllCall($SDL,"int:cdecl","SDL_GL_SetAttribute","ptr",$attr,"int",$value)
   Return $xSDL_GL_SetAttribute[0]
EndFunc

Func SDL_GL_SetSwapInterval($interval)
   Local $xSDL_GL_SetSwapInterval = DllCall($SDL,"int:cdecl","SDL_GL_SetSwapInterval","int",$interval)
   Return $xSDL_GL_SetSwapInterval[0]
EndFunc

Func SDL_GL_SwapWindow($win)
   $xSDL_GL_SwapWindow = DllCall($SDL,"none","SDL_GL_SwapWindow","ptr",$win)
   Return $xSDL_GL_SwapWindow[0]
EndFunc

Func SDL_GL_UnloadLibrary()
   $xSDL_GL_UnloadLibrary = DllCall($SDL,"none","SDL_GL_UnloadLibrary")
   Return $xSDL_GL_UnloadLibrary[0]
EndFunc

Func SDL_GetClosestDisplayMode($display,$mode,$closest)
   Local $xSDL_GetClosestDisplayMode = DllCall($SDL,"ptr:cdecl","SDL_GetClosestDisplayMode","int",$display,"ptr",$mode,"ptr",$closest)
   Return $xSDL_GetClosestDisplayMode[0]
EndFunc

Func SDL_GetCurrentDisplayMode($display,$mode)
  Local $xSDL_GetCurrentDisplayMode = DllCall($SDL,"int:cdecl","SDL_GetCurrentDisplayMode","int",$display,"ptr",$mode)
   Return $xSDL_GetCurrentDisplayMode[0]
EndFunc

Func SDL_GetCurrentVideoDriver()
   $xSDL_GetCurrentVideoDriver = DllCall($SDL,"ptr:cdecl","SDL_GetCurrentVideoDriver")
   Return $xSDL_GetCurrentVideoDriver[0]
EndFunc

Func SDL_GetDesktopDisplayMode($display,$mode)
   Local $xSDL_GetDesktopDisplayMode = DllCall($SDL,"int:cdecl","SDL_GetDesktopDisplayMode","int",$display,"ptr",$mode)
   Return $xSDL_GetDesktopDisplayMode[0]
EndFunc

Func SDL_GetDisplayBounds($display,$xSDL_Rect)
  Local $xSDL_GetDesktopDisplayMode = DllCall($SDL,"int:cdecl","SDL_GetDisplayBounds","int",$display,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_GetDesktopDisplayMode[0]
EndFunc

Func SDL_GetDisplayDPI($display,$ddpi,$hdpi,$vdpi)
  Local $xSDL_GetDisplayDPI = DllCall($SDL,"int:cdecl","SDL_GetDisplayDPI","int",$display,"ptr",$ddpi,"ptr",$hdpi,"ptr",$vdpi)
   Return $xSDL_GetDisplayDPI[0]
EndFunc

Func SDL_GetDisplayMode($display,$modeIndex,$mode)
  Local $xSDL_GetDisplayMode = DllCall($SDL,"int:cdecl","SDL_GetDisplayMode","int",$display,"int",$modeIndex,"ptr",$mode)
   Return $xSDL_GetDisplayMode[0]
EndFunc

Func SDL_GetDisplayName($display)
  Local $xSDL_GetDisplayName = DllCall($SDL,"ptr:cdecl","SDL_GetDisplayName","int",$display)
   Return $xSDL_GetDisplayName[0]
EndFunc

Func SDL_GetDisplayUsableBounds($display,$xSDL_Rect)
   Local $xSDL_GetDisplayUsableBounds = DllCall($SDL,"int:cdecl","SDL_GetDisplayUsableBounds","int",$display,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_GetDisplayUsableBounds[0]
EndFunc

Func SDL_GetGrabbedWindow()
   Local $xSDL_GetGrabbedWindow = DllCall($SDL,"ptr:cdecl","SDL_GetGrabbedWindow")
   Return $xSDL_GetGrabbedWindow[0]
EndFunc

Func SDL_GetNumDisplayModes($display)
   Local $xSDL_GetNumDisplayModes = DllCall($SDL,"int:cdecl","SDL_GetNumDisplayModes","int",$display)
   Return $xSDL_GetNumDisplayModes[0]
EndFunc

Func SDL_GetNumVideoDisplays()
   Local $xSDL_GetNumVideoDisplays = DllCall($SDL,"int:cdecl","SDL_GetNumVideoDisplays")
   Return $xSDL_GetNumVideoDisplays[0]
EndFunc

Func SDL_GetNumVideoDrivers()
   Local $xSDL_GetNumVideoDrivers = DllCall($SDL,"int:cdecl","SDL_GetNumVideoDrivers")
   Return $xSDL_GetNumVideoDrivers[0]
EndFunc

Func SDL_GetVideoDriver($index)
  Local $xSDL_GetVideoDriver = DllCall($SDL,"ptr:cdecl","SDL_GetVideoDriver",$index)
   Return $xSDL_GetVideoDriver[0]
EndFunc

Func SDL_GetWindowBordersSize($win,$top,$left,$bottom,$right)
  Local $xSDL_GetWindowBordersSize = DllCall($SDL,"int:cdecl","SDL_GetWindowBordersSize","ptr",$win,"ptr",$top,"ptr",$left,"ptr",$bottom,"ptr",$right)
   Return $xSDL_GetWindowBordersSize[0]
EndFunc

Func SDL_GetWindowBrightness($win)
   Local $xSDL_GetWindowBrightness = DllCall($SDL,"float:cdecl","SDL_GetWindowBrightness","ptr",$win)
   Return $xSDL_GetWindowBrightness[0]
EndFunc

Func SDL_GetWindowData($win,$name)
   Local $xSDL_GetWindowData = DllCall($SDL,"ptr:cdecl","SDL_GetWindowData","ptr",$win,"ptr",$name)
   Return $xSDL_GetWindowData[0]
EndFunc

Func SDL_GetWindowDisplayIndex($win)
  Local $xSDL_GetWindowDisplayIndex = DllCall($SDL,"int:cdecl","SDL_GetWindowDisplayIndex","ptr",$win)
   Return $xSDL_GetWindowDisplayIndex[0]
EndFunc

Func SDL_GetWindowDisplayMode($win,$mode)
  Local $xSDL_GetWindowDisplayMode = DllCall($SDL,"int:cdecl","SDL_GetWindowDisplayMode","ptr",$win,"ptr",$mode)
   Return $xSDL_GetWindowDisplayMode[0]
EndFunc

Func SDL_GetWindowFlags($win)
   Local $xSDL_GetWindowFlags = DllCall($SDL,"uint:cdecl","SDL_GetWindowFlags","ptr",$win)
   Return $xSDL_GetWindowFlags[0]
EndFunc

Func SDL_GetWindowFromID($id)
  Local $xSDL_GetWindowFromID = DllCall($SDL,"ptr:cdecl","SDL_GetWindowFromID","uint",$id)
   Return $xSDL_GetWindowFromID[0]
EndFunc

Func SDL_GetWindowGammaRamp($win,$r,$g,$b)
   Local $xSDL_GetWindowGammaRamp = DllCall($SDL,"int:cdecl","SDL_GetWindowGammaRamp","ptr",$win,"ptr",$r,"ptr",$g,"ptr",$b)
   Return $xSDL_GetWindowGammaRamp[0]
EndFunc

Func SDL_GetWindowGrab($win)
 Local  $xSDL_GetWinowGrab = DllCall($SDL,"bool:cdecl","SDL_GetWindowGrab","ptr",$win)
   Return $xSDL_GetWindowGrab[0]
EndFunc

Func SDL_GetWindowID($win)
  Local $xSDL_GetWindowID = DllCall($SDL,"uint:cdecl","SDL_GetWindowID","ptr",$win)
   Return $xSDL_GetWindowID[0]
EndFunc

Func SDL_GetWindowMaximumSize($win,$w,$h)
   $xSDL_GetWindowMaximumSize = DllCall($SDL,"none","SDL_GetWindowMaximumSize","ptr",$win,"ptr",$w,"ptr",$h)
   Return $xSDL_GetWindowMaximumSize[0]
EndFunc

Func SDL_GetWindowMinimumSize($win,$w,$h)
   $xSDL_GetWindowMinimumSize = DllCall($SDL,"none","SDL_GetWindowMinimumSize","ptr",$win,"ptr",$w,"ptr",$h)
   Return $xSDL_GetWindowMinimumSize[0]
EndFunc

Func SDL_GetWindowOpacity($win,$opacity)
  Local $xSDL_GetWindowOpacity = DllCall($SDL,"int:cdecl","SDL_GetWindowOpacity","ptr",$win,"ptr",$opacity)
   Return $xSDL_GetWindowOpacity[0]
EndFunc

Func SDL_GetWindowPixelFormat($win)
  Local $xSDL_GetWindowPixelFormat = DllCall($SDL,"uint:cdecl","SDL_GetWindowPixelFormat","ptr",$win)
   Return $xSDL_GetWindowPixelFormat[0]
EndFunc

Func SDL_GetWindowPosition($win,$x,$y)
   $xSDL_GetWindowPosition = DllCall($SDL,"none","SDL_GetWindowPosition","ptr",$win,"pr",$x,"ptr",$y)
   Return $xSDL_GetWindowPosition[0]
EndFunc

Func SDL_GetWindowSize($win,$w,$h)
   $xSDL_GetWindowSize = DllCall($SDL,"none","SDL_GetWindowSize","ptr",$win,"ptr",$x,"ptr",$y)
   Return $xSDL_GetWindowSize[0]
EndFunc

Func SDL_GetWindowSurface($win)
   Local $xSDL_GetWindowSurface = DllCall($SDL,"ptr:cdecl","SDL_GetWindowSurface","ptr",$win)
   Return $xSDL_GetWindowSurface[0]
EndFunc

Func SDL_GetWindowTitle($win)
  Local $xSDL_GetWindowTitle = DllCall($SDL,"ptr:cdecl","SDL_GetWindowTitle","ptr",$win)
   Return $xSDL_GetWindowTitle[0]
EndFunc

Func SDL_GetWindowWMInfo($win,$info)
   Local $xSDL_GetWindowWMInfo = DllCall($SDL,"bool:cdecl","SDL_GetWindowWMInfo","ptr",$win,"ptr",$info)
   Return $xSDL_GetWindowWMInfo[0]
EndFunc

Func SDL_HideWindow($win)
   $xSDL_HideWindow = DllCall($SDL,"none","SDL_HideWindow","ptr",$win)
   Return $xSDL_HideWindow[0]
EndFunc

Func SDL_IsScreenSaverEnabled()
   Local $xSDL_IsScreenSaverEnabled = DllCall($SDL,"bool:cdecl","SDL_IsScreenSaverEnabled")
   Return $xSDL_IsScreenSaverEnabled[0]
EndFunc

Func SDL_MaximizeWindow($win)
   $xSDL_MaximizeWindow = DllCall($SDL,"none","SDL_MaximizeWindow","ptr",$win)
   Return $xSDL_MaximizeWindow[0]
EndFunc

Func SDL_MinimizeWindow($win)
   $xSDL_MinimizeWindow = DllCall($SDL,"none","SDL_MinimizeWindow","ptr",$win)
   Return $xSDL_MinimizeWindow[0]
EndFunc

Func SDL_RaiseWindow($win)
   $xSDL_RaiseWindow = DllCall($SDL,"none","SDL_RaiseWindow","ptr",$win)
   Return $xSDL_RaiseWindow[0]
EndFunc

Func SDL_RestoreWindow($win)
   $xSDL_RestoreWindow = DllCall($SDL,"none","SDL_RestoreWindow","ptr",$win)
   Return $xSDL_RestoreWindow[0]
EndFunc

Func SDL_SetWindowBordered($win,$border)
   $xSDL_SetWindowBordered = DllCall($SDL,"none","SDL_SetWindowBordered","ptr",$win,"bool",$border)
   Return $xSDL_SetWindowBordered[0]
EndFunc

Func SDL_SetWindowBrightness($win,$bright)
   Local $xSDL_SetWindowBrightness = DllCall($SDL,"int:cdecl","SDL_SetWindowBrightness","ptr",$win,"float",$bright)
   Return $xSDL_SetWindowBrightness[0]
EndFunc

Func SDL_SetWindowData($win,$name,$data)
   Local $xSDL_SetWindowData = DllCall($SDL,"ptr:cdecl","SDL_SetWindowData","ptr",$win,"ptr",$name,"ptr",$data)
   Return $xSDL_SetWindowData[0]
EndFunc

Func SDL_SetWindowDisplayMode($win,$mode)
   Local $xSDL_SetWindowDisplayMode = DllCall($SDL,"int:cdecl","SDL_SetWindowDisplayMode","ptr",$win,"ptr",$mode)
   Return $xSDL_SetWindowDisplayMode[0]
EndFunc

Func SDL_SetWindowFullscreen($win,$flags)
   Local $xSDL_SetWindowFullscreen = DllCall($SDL,"int:cdecl","SDL_SetWindowFullscreen","ptr",$win,"uint",$flags)
   Return $xSDL_SetWindowFullscreen[0]
EndFunc

Func SDL_SetWindowGammaRamp($win,$r,$g,$b)
   Local $xSDL_SetWindowGammaRamp = DllCall($SDL,"int:cdecl","SDL_SetWindowGammaRamp","ptr",$win,"ptr",$r,"ptr",$g,"ptr",$b)
   Return $xSDL_SetWindowGammaRamp[0]
EndFunc

Func SDL_SetWindowGrab($win,$grab)
   $xSDL_SetWindowGrab = DllCall($SDL,"none","SDL_SetWindowGrab","ptr",$win,"bool",$grab)
   Return $xSDL_SetWindowGrab[0]
EndFunc

Func SDL_SetWindowHitTest($win,$cb,$dat)
   Local $xSDL_SetWindowHitTest = DllCall($SDL,"int:cdecl","SDL_SetWindowHitTest","ptr",$win,"ptr",$cb,"ptr",$dat)
   Return $xSDL_SetWindowHitTest[0]
EndFunc

Func SDL_SetWindowIcon($win,$icon)
   $xSDL_SetWindowIcon = DllCall($SDL,"none","SDL_SetWindowIcon","ptr",$win,"ptr",$icon)
   Return $xSDL_SetWindowIcon[0]
EndFunc

Func SDL_SetWindowInputFocus($win)
   Local $xSDL_SetWindowInputFocus = DllCall($SDL,"int:cdecl","SDL_SetWindowInputFocus","ptr",$win)
   Return $xSDL_SetWindowInputFocus[0]
EndFunc

Func SDL_SetWindowMaximumSize($win,$w,$h)
   $xSDL_SetWindowMaximumSize = DllCall($SDL,"none","SDL_SetWindowMaximumSize","ptr",$win,"int",$w,"int",$h)
   Return $xSDL_SetWindowMaximumSize[0]
EndFunc

Func SDL_SetWindowMinimumSize($win,$w,$h)
   $xSDL_SetWndowMinimumSize = DllCall($SDL,"none","SDL_SetWindowMinimumSize","ptr",$win,"int",$w,"int",$h)
   Return $xSDL_SetWindowMinimumSize[0]
EndFunc

Func SDL_SetWindowModalFor($win,$win2)
   Local $xSDL_SetWindowModalFor = DllCall($SDL,"int:cdecl","SDL_SetWindowModalFor","ptr",$win,"ptr",$win2)
   Return $xSDL_SetWindowModalFor[0]
EndFunc

Func SDL_SetWindowOpacity($win,$opacity)
  Local $xSDL_SetWindowOpacity = DllCall($SDL,"int:cdecl","SDL_SetWindowOpacity","ptr",$win,"float",$opacity)
   Return $xSDL_SetWindowOpacity[0]
EndFunc

Func SDL_SetWindowPosition($win,$x,$y)
   $xSDL_SetWindowPosition = DllCall($SDL,"none","SDL_SetWindowPosition","ptr",$win,"int",$x,"int",$y)
   Return $xSDL_SetWindowPosition[0]
EndFunc

Func SDL_SetWindowResizable($win,$resize)
   $xSDL_SetWindowResizable = DllCall($SDL,"none","SDL_SetWindowResizable","ptr",$win,"bool",$resize)
   Return $xSDL_SetWindowResizable[0]
EndFunc

Func SDL_SetWindowSize($win,$w,$h)
   $xSDL_SetWindowSize = DllCall($SDL,"none","SDL_SetWindowSize","ptr",$win,"int",$w,"int",$h)
   Return $xSDL_SetWindowSize[0]
EndFunc

Func SDL_SetWindowTitle($win,$title)
   $xSDL_SetWindowTitle = DllCall($SDL,"none","SDL_SetWindowTitle","ptr",$win,"ptr",$title)
   Return $xSDL_SetWindowTitle[0]
EndFunc

Func SDL_ShowMessageBox($mb,$id)
 Local $xSDL_ShowMessageBox = DllCall($SDL,"int:decl","SDL_ShowMessageBox","ptr",$mb,"ptr",$id)
   Return $xSDL_ShowMessageBox[0]
EndFunc

Func SDL_ShowSimpleMessageBox($flags,$title,$msg,$win)
   Local $xSDL_ShowSimpleMessageBox = DllCall($SDL,"int:cdecl","SDL_ShowSimpleMessageBox","uint",$flags,"ptr",$title,"ptr",$msg,"ptr",$win)
   Return $xSDL_ShowSimpleMessageBox[0]
EndFunc

Func SDL_ShowWindow($win)
   $xSDL_ShowWindow = DllCall($SDL,"none","SDL_ShowWindow","ptr",$win)
   Return $xSDL_ShowWindow[0]
EndFunc

Func SDL_UpdateWindowSurface($win)
   Local $xSDL_UpdateWindowSurface = DllCall($SDL,"int:cdecl","SDL_UpdateWindowSurface","ptr",$win)
   Return $xSDL_UpdateWindowSurface[0]
EndFunc

Func SDL_UpdateWindowSurfaceRects($win,$xSDL_Rect,$num)
  Local $xSDL_UpdateWindowSurfaceRects = DllCall($SDL,"int:cdecl","SDL_UpdateWindowSurfaceRects","ptr",$win,"ptr",DllStructGetPtr($xSDL_Rect),"int",$num)
   Return $xSDL_UpdateWindowSurfaceRects[0]
EndFunc

Func SDL_VideoInit($name)
   Local $xSDL_VideoInit = DllCall($SDL,"int:cdecl","SDL_VideoInit","ptr",$name)
   Return $xSDL_VideoInit[0]
EndFunc

Func SDL_VideoQuit()
   $xSDL_VideoQuit = DllCall($SDL,"none","SDL_VideoQuit")
   Return $xSDL_VideoQuit[0]
EndFunc

;SDL Hints
Func SDL_AddHintCallback($name, $cb,$dat)
   $xSDL_AddHintCallback = DllCall($SDL,"none","SDL_AddHintCallback","ptr",$name,"ptr",$cb,"ptr",$dat)
   Return $xSDL_AddHintCallback[0]
EndFunc

Func SDL_ClearHints()
   $xSDL_ClearHints = DllCall($SDL,"none","SDL_ClearHints","none")
   Return $xSDL_ClearHints[0]
EndFunc

Func SDL_DelHintCallback($name,$cb,$dat)
   $xSDL_DelHintCallback = DllCall($SDL,"none","SDL_DelHintCallback","ptr",$name,"ptr",$cb,"ptr",$dat)
   Return $xSDL_DelHintCallback[0]
EndFunc

Func SDL_GetHint($name)
   Local $xSDL_GetHint = DllCall($SDL,"ptr:cdecl","SDL_GetHint","ptr",$name)
   Return $xSDL_GetHint[0]
EndFunc

Func SDL_GetHintBoolean($name,$val)
   Local $xSDL_GetHintBoolean = DllCall($SDL,"bool:cdecl","SDL_GetHintBoolean","ptr",$name,"bool",$val)
   Return $xSDL_GetHintBoolean[0]
EndFunc

Func SDL_SetHint($name,$val)
   Local $xSDL_SetHint = DllCall($SDL,"bool:cdecl","SDL_SetHint","ptr",$name,"ptr",$val)
   Return $xSDL_SetHint[0]
EndFunc

Func SDL_SetHintWithPriority($name,$val,$prio)
   Local $xSDL_SetHintWithPriority = DllCall($SDL,"bool:cdecl","SDL_SetHintWithPriority","ptr",$name,"ptr",$val,"ptr",$prio)
   Return $xSDL_SetHintWithPriority[0]
EndFunc

;SDL Error
Func SDL_ClearError()
   Local $xSDL_ClearError = DllCall($SDL,"none","SDL_ClearError")
   Return $xSDL_ClearError[0]
EndFunc

Func SDL_GetError()
   Local $xSDL_GetError = DllCall($SDL,"ptr:cdecl","SDL_GetError")
   Return $xSDL_GetError[0]
EndFunc

Func SDL_SetError($fmt,$x)
   Local $xSDL_SetError = DllCall($SDL,"int:cdecl","SDL_SetError","ptr",$fmt,"ptr",$x)
   Return $xSDL_SetError[0]
EndFunc

;SDL Log
Func SDL_Log($fmt,$x)
   Local $xSDL_Log = DllCall($SDL,"none","SDL_Log","ptr",$fmt,"ptr",$x)
   Return $xSDL_Log[0]
EndFunc

Func SDL_LogCritical($cat,$fmt,$x)
   Local $xSDL_LogCritical = DllCall($SDL,"none","SDL_LogCritical","int",$cat,"ptr",$fmt,"ptr",$x)
   Return $xSDL_LogCritical[0]
EndFunc

Func SDL_LogDebug($cat,$fmt,$x)
   Local $xSDL_LogDebug = DllCall($SDL,"none","SDL_LogDebug","int",$cat,"ptr",$fmt,"ptr",$x)
   Return $xSDL_LogDebug[0]
EndFunc

Func SDL_LogError($cat,$fmt,$x)
   Local $xSDL_LogError = DllCall($SDL,"none","SDL_LogError","int",$cat,"ptr",$fmt,"ptr",$x)
   Return $xSDL_LogError[0]
EndFunc

Func SDL_LogGetOutputFunction($cb,$ud)
   Local $xSDL_LogGetOutputFunction = DllCall($SDL,"none","ptr",$cb,"ptr",$ud)
   Return $xSDL_LogGetOutputFunction[0]
EndFunc

Func SDL_LogGetPriority($cat)
   Local $xSDL_LogGetPriority = DllCall($SDL,"ptr:cdecl","int",$cat)
   Return $xSDL_LogGetPriority[0]
EndFunc

Func SDL_LogInfo($cat,$fmt,$x)
   Local $xSDL_LogInfo = DllCall($SDL,"none","int",$cat,"ptr",$fmt,"ptr",$x)
   Return $xSDL_LogInfo[0]
EndFunc

Func SDL_LogMessage($cat,$pri,$fmt,$x)
   Local $xSDL_LogMessage = DllCall($SDL,"none","int",$cat,"ptr",$pri,"ptr",$fmt,"ptr",$x)
   Return $xSDL_LogMessage[0]
EndFunc

Func SDL_LogMessageV($cat,$pri,$fmt,$ap)
   Local $xSDL_LogMessageV = DllCall($SDL,"none","int",$cat,"ptr",$pri,"ptr",$fmt,"ptr",$ap)
   Return $xSDL_LogMessageV[0]
EndFunc

Func SDL_LogResetPriorities()
   Local $xSDL_LogResetPriorities = DllCall($SDL,"none","SDL_LogResetPriorities")
   Return $xSDL_LogResetPriorities[0]
EndFunc

Func SDL_LogSetAllPriority($pri)
   Local $xSDL_LogSetAllPriority = DllCall($SDL,"none","SDL_LogSetAllPriority","ptr",$pri)
   Return $xSDL_LogSetAllPriority[0]
EndFunc

Func SDL_LogSetOutputFunction($fun,$x)
   Local $xSDL_LogSetAllPriority = DllCall($SDL,"none","SDL_LogSetOutputFunction","ptr",$fun,"ptr",$x)
   Return $xSDL_LogSetAllPriority[0]
EndFunc

Func SDL_LogSetPriority($cat,$pri)
   Local $xSDL_LogSetPriority = DllCall($SDL,"none","SDL_LogSetPriority","int",$cat,"ptr",$pri)
   Return $xSDL_LogSetPriority[0]
EndFunc

Func SDL_LogVerbose($cat,$fmt,$x)
   Local $xSDL_LogVerbose = DllCall($SDL,"none","SDL_LogVerbose","int",$cat,"ptr",$fmt,"ptr",$x)
   Return $xSDL_LogVerbose[0]
EndFunc

Func SDL_LogWarn($cat,$fmt,$x)
   Local $xSDL_LogWarn = DllCall($SDL,"none","SDL_LogWarn","int",$cat,"ptr",$fmt,"ptr",$x)
   Return $xSDL_LogWarn[0]
EndFunc

;SDL Assertion Funcs
Func SDL_AssertionHandler($ud)
   Local $xSDL_AssertionHandler = DllCall($SDL,"ptr:cdecl","SDL_AssertionHandler","ptr",$ud)
   Return $xSDL_AssertionHandler[0]
EndFunc

Func SDL_GetAssertionReport()
   Local $xSDL_GetAssertionReport = DllCall($SDL,"ptr:cdecl","SDL_GetAssertionReport")
   Return $xSDL_GetAssertionReport[0]
EndFunc

Func SDL_GetDefaultAssertionHandler()
   Local $xSDL_GetDefaultAssertionHandler = DllCall($SDL,"ptr:cdecl","SDL_GetDefaultAssertionHandler")
   Return $xSDL_GetDefaultAssertionHandler[0]
EndFunc

Func SDL_ResetAssertionReport()
   Local $xSDL_ResetAssertionReport = DllCall($SDL,"none","SDL_ResetAssertionReport")
   Return $xSDL_ResetAssertionReport[0]
EndFunc

Func SDL_SetAssertionHandler($hand,$ud)
   Local $xSDL_SetAssertionHandler = DllCall($SDL,"none","SDL_SetAssertionHandler","ptr",$hand,"ptr",$ud)
   Return $xSDL_SetAssertionHandler[0]
EndFunc

Func SDL_TriggerBreakpoint()
   Local $xSDL_TriggerBreakpoint = DllCall($SDL,"none","SDL_TriggerBreakpoint")
   Return $xSDL_TriggerBreakpoint[0]
EndFunc

Func SDL_assert($x)
   Local $xSDL_assert = DllCall($SDL,"none","SDL_assert")
   Return $xSDL_assert[0]
EndFunc

Func SDL_assert_paranoid($x)
   Local $xSDL_assert_paranoid = DllCall($SDL,"none","SDL_assert_paranoid")
   Return $xSDL_assert_paranoid[0]
EndFunc

Func SDL_assert_release($x)
   Local $xSDL_assert_release = DllCall($SDL,"none","SDL_assert_release")
   Return $xSDL_assert_release[0]
EndFunc

;SDL Version Query
Func SDL_GetRevision()
   Local $xSDL_GetRevision = DllCall($SDL,"ptr:cdecl","SDL_GetRevision")
   Return $xSDL_GetRevision[0]
EndFunc

Func SDL_GetRevisionNumber()
   Local $xSDL_GetRevisionNumber = DllCall($SDL,"int:cdecl","SDL_GetRevisionNumber")
   Return $xSDL_GetRevisionNumber[0]
EndFunc

Func SDL_GetVersion($ver)
   Local $xSDL_GetVersion = DllCall($SDL,"none","SDL_GetVersion","ptr",$ver)
   Return $xSDL_GetVersion[0]
EndFunc

;SDL Render
Func SDL_CreateRenderer($win,$index,$flags)
   Local $xSDL_CreateRenderer = DllCall($SDL,"ptr:cdecl","SDL_CreateRenderer","ptr",$win,"int",$index,"uint",$flags)
   Return $xSDL_CreateRenderer[0]
EndFunc

Func SDL_CreateSoftwareRenderer($surf)
   Local $xSDL_CreateSoftwareRenderer = DllCall($SDL,"ptr:cdecl","SDL_CreateSoftwareRenderer","ptr",$surf)
   Return $xSDL_CreateSoftwareRenderer[0]
EndFunc

Func SDL_CreateTexture($ren,$format,$access,$w,$h)
   Local $xSDL_CreateTexture = DllCall($SDL,"ptr:cdecl","SDL_CreateTexture","ptr",$ren,"uint",$format,"int",$access,"int",$w,"int",$h)
   Return $xSDL_CreateTexture[0]
EndFunc

Func SDL_CreateTextureFromSurface($ren,$surf)
   Local $xSDL_CreateTextureFromSurface = DllCall($SDL,"ptr:cdecl","SDL_CreateTextureFromSurface","ptr",$ren,"ptr",$surf)
   Return $xSDL_CreateTextureFromSurface[0]
EndFunc

;Duplicate in the Render function list
;Func SDL_CreateWindowAndRenderer($w,$h,$flags,$win,$ren)
 ;  Local $xSDL_CreateWindowAndRenderer = DllCall($SDL,"int:cdecl","SDL_CreateWindowAndRenderer","int",$w,"int",$h,"uint",$flags,"ptr",$win,"ptr",$ren)
  ; Return $xSDL_CreateWindowAndRenderer[0]
;EndFunc

Func SDL_DestroyRenderer($ren)
   Local $xSDL_DestroyRenderer = DllCall($SDL,"none","SDL_DestroyRenderer","ptr",$ren)
   Return $xSDL_DestroyRenderer[0]
EndFunc

Func SDL_DestroyTexture($tex)
   Local $xSDL_DestroyTexture = DllCall($SDL,"none","SDL_DestroyTexture","ptr",$tex)
   Return $xSDL_DestroyTexture[0]
EndFunc

Func SDL_GL_BindTexture($tex,$w,$h)
   Local $xSDL_GL_BindTexture = DllCall($SDL,"int:cdecl","SDL_GL_BindTexture","ptr",$tex,"ptr",$w,"ptr",$h)
   Return $xSDL_GL_BindTexture[0]
EndFunc

Func SDL_GL_UnbindTexture($tex)
   Local $xSDL_GL_UnbindTexture = DllCall($SDL,"int:cdecl","SDL_GL_UnbindTexture","ptr",$tex)
   Return $xSDL_GL_UnbindTexture[0]
EndFunc

Func SDL_GetNumRenderDrivers()
   Local $xSDL_GetNumRenderDrivers = DllCall($SDL,"int:cdecl","SDL_GetNumRenderDrivers")
   Return $xSDL_GetNumRenderDrivers[0]
EndFunc

Func SDL_GetRenderDrawBlendMode($ren,$mode)
   Local $xSDL_GetRenderDrawBlendMode = DllCall($SDL,"int:cdecl","ptr",$ren,"ptr",$mode)
   Return $xSDL_GetRenderDrawBlendMode[0]
EndFunc

Func SDL_GetRenderDrawColor($ren,$r,$g,$b,$a)
   Local $xSDL_GetRenderDrawColor = DllCall($SDL,"int:cdecl","SDL_GetRenderDrawColor","ptr",$ren,"ptr",$r,"ptr",$g,"ptr",$b,"ptr",$a)
   Return $xSDL_GetRenderDrawColor[0]
EndFunc

Func SDL_GetRenderDriverInfo($idx,$info)
   Local $xSDL_GetRenderDriverInfo = DllCall($SDL,"int:cdecl","SDL_GetRenderDriverInfo","int",$idx,"ptr",$info)
   Return $xSDL_GetRenderDriverInfo[0]
EndFunc

Func SDL_GetRenderTarget($ren)
   Local $xSDL_GetRenderTarget = DllCall($SDL,"ptr:cdecl","SDL_GetRenderTarget","ptr",$ren)
   Return $xSDL_GetRenderTarget[0]
EndFunc

Func SDL_GetRenderer($win)
   Local $xSDL_GetRenderer = DllCall($SDL,"ptr:cdecl","SDL_GetRenderer","ptr",$win)
   Return $xSDL_GetRenderer[0]
EndFunc

Func SDL_GetRendererInfo($ren,$info)
   Local $xSDL_GetRendererInfo = DllCall($SDL,"int:cdecl","SDL_GetRendererInfo","ptr",$ren,"ptr",$info)
   Return $xSDL_GetRendererInfo[0]
EndFunc

Func SDL_GetRendererOutputSize($ren,$w,$h)
   Local $xSDL_GetRendererOutputSize = DllCall($SDL,"int:cdecl","SDL_GetRendererOutputSize","ptr",$ren,"ptr",$w,"ptr",$h)
   Return $xSDL_GetRendererOutputSize[0]
EndFunc

Func SDL_GetTextureAlphaMod($tex,$al)
   Local $xSDL_GetTextureAlphaMod = DllCall($SDL,"int:cdecl","SDL_GetTextureAlphaMod","ptr",$ren,"ptr",$al)
   Return $xSDL_GetTextureAlphaMod[0]
EndFunc

Func SDL_GetTextureBlendMode($tex,$mode)
   Local $xSDL_GetTextureBlendMode = DllCall($SDL,"int:cdecl","SDL_GetTextureBlendMode","ptr",$tex,"ptr",$mode)
   Return $xSDL_GetTextureBlendMode[0]
EndFunc

Func SDL_GetTextureColorMod($tex,$r,$g,$b)
   Local $xSDL_GetTextureColorMod = DllCall($SDL,"int:cdecl","SDL_GetTextureColorMod","ptr",$ren,"ptr",$r,"ptr",$g,"ptr",$b)
   Return $xSDL_GetTextureColorMod[0]
EndFunc

Func SDL_LockTexture($tex,$xSDL_Rect,$pix,$pit)
   Local $xSDL_LockTexture = DllCall($SDL,"int:cdecl","SDL_LockTexture","ptr",$tex,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",$pix,"ptr",$pit)
   Return $xSDL_LockTexture[0]
EndFunc

Func SDL_QueryTexture($tex,$mat,$acc,$w,$h)
   Local $xSDL_QueryTexture = DllCall($SDL,"int:cdecl","SDL_QueryTexture","ptr",$tex,"ptr",$mat,"ptr",$acc,"ptr",$w,"ptr",$h)
   Return $xSDL_QueryTexture[0]
EndFunc

Func SDL_RenderClear($ren)
   Local $xSDL_RenderClear = DllCall($SDL,"int:cdecl","SDL_RenderClear","ptr",$ren)
   Return $xSDL_RenderClear[0]
EndFunc

Func SDL_RenderCopy($ren,$tex,$xSDL_Rect,$xSDL_Rect2)
   Local $xSDL_RenderCopy = DllCall($SDL,"int:cdecl","SDL_RenderCopy","ptr",$ren,"ptr",$tex,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_RenderCopy[0]
EndFunc

Func SDL_RenderCopyEx($ren,$tex,$xSDL_Rect,$xSDL_Rect2,$angle,$center,$flip)
   Local $xSDL_RenderCopyEx = DllCall($SDL,"int:cdecl","SDL_RenderCopyEx","ptr",$ren,"ptr",$tex,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",DllStructGetPtr($xSDL_Rect2),"double",$angle,"ptr",$center,"ptr",$flip)
   Return $xSDL_RenderCopyEx[0]
EndFunc

Func SDL_RenderDrawLine($ren,$x,$y,$x2,$y2)
   Local $xSDL_RenderDrawLine = DllCall($SDL,"int:cdecl","ptr",$ren,"int",$x,"int",$y,"int",$x2,"int",$y2)
   Return $xSDL_RenderDrawLine[0]
EndFunc

Func SDL_RenderDrawLines($ren,$pt,$count)
   Local $xSDL_RenderDrawLines = DllCall($SDL,"int:cdecl","ptr",$ren,"ptr",$pt,"int",$count)
   Return $xSDL_RenderDrawLines[0]
EndFunc

Func SDL_RenderDrawPoint($ren,$x,$y)
   Local $xSDL_RenderDrawPoint = DllCall($SDL,"int:cdecl","ptr",$ren,"int",$x,"int",$y)
   Return $xSDL_RenderDrawPoint[0]
EndFunc

Func SDL_RenderDrawPoints($ren,$pt,$count)
   Local $xSDL_RenderDrawPoints = DllCall($SDL,"int:cdecl","ptr",$ren,"ptr",$pt,"int",$count)
   Return $xSDL_RenderDrawPoints[0]
EndFunc

Func SDL_RenderDrawRect($ren,$xSDL_Rect)
   Local $xSDL_RenderDrawRect = DllCall($SDL,"int:cdecl","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_RenderDrawRect[0]
EndFunc

Func SDL_RenderDrawRects($ren,$xSDL_Rect,$count)
   Local $xSDL_RenderDrawRects = DllCall($SDL,"int:cdecl","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect),"int",$count)
   Return $xSDL_RenderDrawRects[0]
EndFunc

Func SDL_RenderFillRect($ren,$xSDL_Rect)
   Local $xSDL_RenderFillRect = DllCall($SDL,"int:cdecl","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_RenderFillRect[0]
EndFunc

Func SDL_RenderFillRects($ren,$xSDL_Rect,$count)
   Local $xSDL_RenderFillRects = DllCall($SDL,"int:cdecl","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect),"int",$count)
   Return $xSDL_RenderFillRects[0]
EndFunc

Func SDL_RenderGetClipRect($ren,$xSDL_Rect)
   Local $xSDL_RenderGetClipRect = DllCall($SDL,"none","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_RenderGetClipRect[0]
EndFunc

Func SDL_RenderGetIntegerScale($ren)
   Local $xSDL_RenderGetIntegerScale = DllCall($SDL,"bool:cdecl","SDL_RenderGetIntegerScale","ptr",$ren)
   Return $xSDL_RenderGetIntegerScale[0]
EndFunc

Func SDL_RenderGetLogicalSize($ren,$w,$h)
   Local $xSDL_RenderGetLogicalSize = DllCall($SDL,"none","SDL_RenderGetLogicalSize","ptr",$ren,"ptr",$w,"ptr",$h)
   Return $xSDL_RenderGetLogicalSize[0]
EndFunc

Func SDL_RenderGetScale($ren,$x,$y)
   Local $xSDL_RenderGetScale = DllCall($SDL,"none","SDL_RenderGetScale","ptr",$ren,"ptr",$x,"ptr",$y)
   Return $xSDL_RenderGetScale[0]
EndFunc

Func SDL_RenderGetViewport($ren,$xSDL_Rect)
   Local $xSDL_RenderGetViewport = DllCall($SDL,"none","SDL_RenderGetViewport","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_RenderGetViewport[0]
EndFunc

Func SDL_RenderIsClipEnabled($ren)
   Local $xSDL_RenderIsClipEnabled = DllCall($SDL,"bool:cdecl","SDL_RenderIsClipEnabled","ptr",$ren)
   Return $xSDL_RenderIsClipEnabled[0]
EndFunc

Func SDL_RenderPresent($ren)
   Local $xSDL_RenderPresent = DllCall($SDL,"none","SDL_RenderPresent","ptr",$ren)
   Return $xSDL_RenderPresent[0]
EndFunc

Func SDL_RenderReadPixels($ren,$xSDL_Rect,$mat,$pix,$pit)
   Local $xSDL_RenderReadPixels = DllCall($SDL,"int:cdecl","SDL_RenderReadPixels","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect),"unit",$mat,"ptr",$pix,"int",$pit)
   Return $xSDL_RenderReadPixels[0]
EndFunc

Func SDL_RenderSetClipRect($ren,$xSDL_Rect)
   Local $xSDL_RenderSetClipRect = DllCall($SDL,"int:cdecl","SDL_RenderSetClipRect","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_RenderSetClipRect[0]
EndFunc

Func SDL_RenderSetIntegerScale($ren,$enable)
   Local $xSDL_RenderSetIntegerScale = DllCall($SDL,"int:cdecl","SDL_RenderSetIntegerScale","ptr",$ren,"bool",$enable)
   Return $xSDL_RenderSetIntegerScale[0]
EndFunc

Func SDL_RenderSetLogicalSize($ren,$w,$h)
   Local $xSDL_RenderSetLogicalSize = DllCall($SDL,"int:cdecl","SDL_RenderSetLogicalSize","ptr",$ren,"int",$w,"int",$h)
   Return $xSDL_RenderSetLogicalSize[0]
EndFunc

Func SDL_RenderSetScale($ren,$x,$y)
   Local $xSDL_RenderSetScale = DllCall($SDL,"int:cdecl","SDL_RenderSetScale","ptr",$ren,"float",$x,"float",$y)
   Return $xSDL_RenderSetScale[0]
EndFunc

Func SDL_RenderSetViewport($ren,$xSDL_Rect)
   Local $xSDL_RenderSetViewport = DllCall($SDL,"int:cdecl","SDL_RenderSetViewport","ptr",$ren,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_RenderSetViewport[0]
EndFunc

Func SDL_RenderTargetSupported($ren)
   Local $xSDL_RenderTargetSupported = DllCall($SDL,"bool:cdecl","SDL_RenderTargetSupported","ptr",$ren)
   Return $xSDL_RenderTargetSupported[0]
EndFunc

Func SDL_SetRenderDrawBlendMode($ren,$mode)
   Local $xSDL_SetRenderDrawBlendMode = DllCall($SDL,"int:cdecl","SDL_SetRenderDrawBlendMode","ptr",$ren,"ptr",$mode)
   Return $xSDL_SetRenderDrawBlendMode[0]
EndFunc

Func SDL_SetRenderDrawColor($ren,$r,$g,$b,$a)
   Local $xSDL_SetRenderDrawColor = DllCall($SDL,"int:cdecl","SDL_SetRenderDrawColor","ptr",$ren,"uint",$r,"uint",$g,"uint",$b,"uint",$a)
   Return $xSDL_SetRenderDrawColor[0]
EndFunc

Func SDL_SetRenderTarget($ren,$tex)
   Local $xSDL_SetRenderTarget = DllCall($SDL,"int:cdecl","SDL_SetRenderTarget","ptr",$ren,"ptr",$tex)
   Return $xSDL_SetRenderTarget[0]
EndFunc

Func SDL_SetTextureAlphaMod($tex,$al)
   Local $xSDL_SetTextureAlphaMod = DllCall($SDL,"int:cdecl","SDL_SetTextureAlphaMod","ptr",$tex,"uint",$al)
   Return $xSDL_SetTextureAlphaMod[0]
EndFunc

Func SDL_SetTextureBlendMode($tex,$mode)
   Local $xSDL_SetTextureBlendMode = DllCall($SDL,"int:cdecl","SDL_SetTextureBlendMode","ptr",$tex,"ptr",$mode)
   Return $xSDL_SetTextureBlendMode[0]
EndFunc

Func SDL_SetTextureColorMod($tex,$r,$g,$b)
   Local $xSDL_SetTextureColorMod = DllCall($SDL,"int:cdecl","SDL_SetTextureColorMod","ptr",$tex,"uint",$r,"uint",$g,"uint",$b)
   Return $xSDL_SetTextureColorMod[0]
EndFunc

Func SDL_UnlockTexture($tex)
   Local $xSDL_UnlockTexture = DllCall($SDL,"none","SDL_UnlockTexture","ptr",$tex)
   Return $xSDL_UnlockTexture[0]
EndFunc

Func SDL_UpdateTexture($tex,$xSDL_Rect,$pix,$pit)
   Local $xSDL_UpdateTexture = DllCall($SDL,"int:cdecl","SDL_UpdateTexture","ptr",$tex,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",$pix,"int",$pit)
   Return $xSDL_UpdateTexture[0]
EndFunc

Func SDL_UpdateYUVTexture($tex,$xSDL_Rect,$yplane,$ypit,$uplane,$upit,$vplane,$vpit)
   Local $xSDL_UpdateYUVTexture = DllCall($SDL,"int:cdelc","SDL_UpdateYUVTexture","ptr",$tex,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",$yplane,"int",$ypit,"ptr",$uplane,"int",$upit,"ptr",$vplane,"int",$vpit)
   Return $xSDL_UpdateYUVTexture[0]
EndFunc

;Pixel Functions

Func SDL_AllocFormat($pix)
   Local $xSDL_AllocFormat = DllCall($SDL,"ptr:cdecl","SDL_AllocFormat","uint",$pix)
   Return $xSDL_AllocFormat[0]
EndFunc

Func SDL_AllocPalette($cols)
   Local $xSDL_AllocPalette = DllCall($SDL,"ptr:cdecl","SDL_AllocPalette","int",$cols)
   Return $xSDL_AllocPalette[0]
EndFunc

Func SDL_CalculateGammaRamp($gam,$ram)
   Local $xSDL_CalculateGammaRamp = DllCall($SDL,"none","SDL_CalculateGammaRamp","float",$gam,"ptr",$ram)
   Return $xSDL_CalculateGammaRamp[0]
EndFunc

Func SDL_FreeFormat($mat)
   Local $xSDL_FreeFormat = DllCall($SDL,"none","SDL_FreeFormat","ptr",$mat)
   Return $xSDL_FreeFormat[0]
EndFunc

Func SDL_FreePalette($pal)
   Local $xSDL_FreePalette = DllCall($SDL,"none","SDL_FreePalette","ptr",$pal)
   Return $xSDL_FreePalette[0]
EndFunc

Func SDL_GetPixelFormatName($mat)
   Local $xSDL_GetPixelFormatName = DllCall($SDL,"ptr:cdecl","SDL_GetPixelFormatName","uint",$mat)
   Return $xSDL_GetPixelFormatName[0]
EndFunc

Func SDL_GetRGB($pix,$mat,$r,$g,$b)
   Local $xSDL_GetRGB = DllCall($SDL,"none","SDL_GetRGB","uint",$pix,"ptr",$mat,"ptr",$r,"ptr",$g,"ptr",$b)
   Return $xSDL_GetRGB[0]
EndFunc

Func SDL_GetRGBA($pix,$matr,$r,$g,$b,$a)
   Local $xSDL_GetRGBA = DllCall($SDL,"none","SDL_GetRGBA","uint",$pix,"ptr",$mat,"ptr",$r,"ptr",$g,"ptr",$b,"ptr",$a)
   Return $xSDL_GetRGBA[0]
EndFunc

Func SDL_MapRGB($mat,$r,$g,$b)
   Local $xSDL_MapRGB = DllCall($SDL,"uint:cdecl","SDL_MapRGB","ptr",$mat,"uint",$r,"uint",$g,"uint",$b)
   Return $xSD_MapRGB[0]
EndFunc

Func SDL_MapRGBA($mat,$r,$g,$b,$a)
   Local $xSDL_MapRGBA = DllCall($SDL,"uint:cdecl","SDL_MapRGBA","ptr",$mat,"uint",$r,"uint",$g,"uint",$b,"uint",$a)
   Return $xSDL_MapRGBA[0]
EndFunc

Func SDL_MasksToPixelFormatEnum($bpp,$r,$g,$b,$a)
   Local $xSDL_MasksToPixelFormatEnum = DllCall($SDL,"uint:cdecl","SDL_MasksToPixelFormatEnum","int",$bpp,"uint",$r,"uint",$g,"uint",$b,"uint",$a)
   Return $xSDL_MasksToPixelFormatEnum[0]
EndFunc

Func SDL_PixelFormatEnumToMasks($mat,$bpp,$r,$g,$b,$a)
   Local $xSDL_PixelFormatEnumToMasks = DllCall($SDL,"bool:cdecl","SDL_PixelFormatEnumToMasks","uint",$mat,"ptr",$bpp,"ptr",$r,"ptr",$g,"ptr",$b,"ptr",$a)
   Return $xSDL_PixelFormatEnumToMasks[0]
EndFunc

Func SDL_SetPaletteColors($pal,$col,$first,$co2)
   Local $xSDL_SetPaletteColors = DllCall($SDL,"int:cdecl","SDL_SetPaletteColors","ptr",$pal,"ptr",$col,"int",$first,"int",$col2)
   Return $xSDL_SetPaletteColors[0]
EndFunc

Func SDL_SetPixelFormatPalette($mat,$pal)
   Local $xSDL_SetPixelFormatPalette = DllCall($SDL,"int:cdecl","SDL_SetPixelFormatPalette","ptr",$mat,"ptr",$pal)
   Return $xSDL_SetPixelFormatPalette[0]
EndFunc

;Rect functions
Func SDL_EnclosePoints($pt,$count,$xSDL_Rect,$xSDL_Rect2)
   Local $xSDL_EnclosePoints = DllCall($SDL,"bool:cdecl","SDL_EnclosePoints","ptr",$pt,"int",$count,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_EnclosePoints[0]
EndFunc

Func SDL_HasIntersection($xSDL_Rect,$xSDL_Rect2)
   Local $xSDL_HasIntersection = DllCall($SDL,"bool:cdecl","SDL_HasIntersection","ptr",DllStructGetPtr($xSDL_Rect),"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_HasIntersection[0]
EndFunc

Func SDL_IntersectRect($xSDL_Rect,$xSDL_Rect2,$xSDL_Rect3)
   Local $xSDL_IntersectRect = DllCall($SDL,"bool:cdecl","SDL_IntersectRect","ptr",DllStructGetPtr($xSDL_Rect),"ptr",DllStructGetPtr($xSDL_Rect2),"ptr",DllStructGetPtr($xSDL_Rect3))
   Return $xSDL_IntersectRect[0]
EndFunc

Func SDL_IntersectRectAndLine($xSDL_Rect,$x,$y,$x2,$y2)
   Local $xSDL_IntersectRectAndLine = DllCall($SDL,"bool:cdecl","SDL_IntersectRectAndLine","ptr",DllStructGetPtr($xSDL_Rect),"ptr",$x,"ptr",$y,"ptr",$x2,"ptr",$y2)
   Return $xSDL_IntersectRectAndLine[0]
EndFunc

Func SDL_PointInRect($xSDL_Rect,$xSDL_Rect2)
   Local $xSDL_PointInRect = DllCall($SDL,"bool:cdecl","SDL_PointInRect","ptr",DllStructGetPtr($xSDL_Rect),"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_PointInRect[0]
EndFunc

Func SDL_RectEmpty($xSDL_Rect)
   Local $xSDL_RectEmpty = DllCall($SDL,"bool:cdecl","SDL_RectEmpty","ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_RectEmpty[0]
EndFunc

Func SDL_RectEquals($xSDL_Rect,$xSDL_Rect2)
   Local $xSDL_RectEquals = DllCall($SDL,"bool:cdecl","SDL_RectEquals","ptr",DllStructGetPtr($xSDL_Rect,"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_RectEquals[0]
EndFunc

Func SDL_UnionRect($xSDL_Rect,$xSDL_Rect2,$xSDL_Rect3)
   Local $xSDL_UnionRect = DllCall($SDL,"none","SDL_UnionRect","ptr",DllStructGetPtr($xSDL_Rect),"ptr",DllStructGetPtr($xSDL_Rect2),"ptr",DllStructGetPtr($xSDL_Rect3))
   Return $xSDL_UnionRect[0]
EndFunc

;SDL RWops Functions

Func SDL_AllocRW()
   Local $xSDL_AllocRW = DllCall($SDL,"ptr:cdecl","SDL_AllocRW")
   Return $xSDL_AllocRW[0]
EndFunc

Func SDL_FreeRW($rw)
   Local $xSDL_FreeRW = DllCall($SDL,"none","SDL_FreeRW","ptr",$rw)
   Return $xSDL_FreeRW[0]
EndFunc

Func SDL_RWFromConstMem($mem,$size)
   Local $xSDL_RWFromConstMem = DllCall($SDL,"ptr:cdecl","SDL_RWFromConstMem","ptr",$mem,"int",$size)
   Return $xSDL_RWFromConstMen[0]
EndFunc

Func SDL_RWFromFP($fp,$cls)
   Local $xSDL_RWFromFP = DllCall($SDL,"ptr:cdecl","SDL_RWFromFP","ptr",$fp,"bool",$cls)
   Return $xSDL_RWFromFP[0]
EndFunc

Func SDL_RWFromFile($file,$mode)
   Local $xSDL_RWFromFile = DllCall($SDL,"ptr:cdecl","ptr",$fp,"ptr",$mode)
   Return $xSDL_RWFromFile[0]
EndFunc

Func SDL_RWFromMem($mem,$size)
   Local $xSDL_RWFromMem = DllCall($SDL,"ptr:cdecl","SDL_RWFromMem","ptr",$mem,"int",$size)
   Return $xSDL_RWFromMen[0]
EndFunc

Func SDL_RWclose($ctx)
   Local $xSDL_RWclose = DllCall($SDL,"int:cdecl","SDL_RWclose","ptr",$ctx)
   Return $xSDL_RWclose[0]
EndFunc

Func SDL_RWread($ctx,$p,$size,$max)
   Local $xSDL_RWread = DllCall($SDL,"ulong_ptr:cdecl","SDL_RWread","ptr",$ctx,"ptr",$p,"ulong_ptr",$size,"ulong_ptr",$max)
   Return $xSDL_RWread[0]
EndFunc

Func SDL_RWseek($ctx,$off,$when)
   Local $xSDL_Rwseek = DllCall($SDL,"int64:cdecl","SDL_RWseek","ptr",$ctx,"int64",$off,"int",$when)
   Return $xSDL_RWseek[0]
EndFunc

Func SDL_RWsize($ctx)
   Local $xSDL_RWsize = DllCall($SDL,"int64:cdecl","SDL_RWsize","ptr",$ctx)
   Return $xSDL_RWsize[0]
EndFunc

Func SDL_RWtell($ctx)
   Local $xSDL_RWtell = DllCall($SDL,"int64:cdecl","SDL_RWtell","ptr",$ctx)
   Return $xSDL_RWtell[0]
EndFunc

Func SDL_RWwrite($ctx,$p,$size,$num)
   Local $xSDL_RWwrite = DllCall($SDL,"ulong_ptr:cdecl","SDL_RWwrite","ptr",$ctx,"ptr",$p,"ulong_ptr",$size,"ulong_ptr",$num)
   Return $xSDL_REwrite[0]
EndFunc

Func SDL_ReadBE16($src)
   Local $xSDL_ReadBE16 = DllCall($SDL,"uint:cdecl","SDL_ReadBE16","ptr",$src)
   Return $xSDL_ReadBE16[0]
EndFunc

Func SDL_ReadBE32($src)
   Local $xSDL_ReadBE32 = DllCall($SDL,"uint:cdecl","SDL_ReadBE32","ptr",$src)
   Return $xSDL_ReadBE32[0]
EndFunc

Func SDL_ReadBE64($src)
   Local $xSDL_ReadBE64 = DllCall($SDL,"uint:cdecl","SDL_ReadBE64","ptr",$src)
   Return $xSDL_ReadBE64[0]
EndFunc

Func SDL_ReadLE16($src)
   Local $xSDL_ReadLE16 = DllCall($SDL,"uint:cdecl","SDL_ReadLE16","ptr",$src)
   Return $xSDL_ReadLE16[0]
EndFunc

Func SDL_ReadLE32($src)
   Local $xSDL_ReadLE32 = DllCall($SDL,"uint:cdecl","SDL_ReadLE32","ptr",$src)
   Return $xSDL_ReadLE32[0]
EndFunc

Func SDL_ReadLE64($src)
   Local $xSDL_ReadLE64 = DllCall($SDL,"uint:cdecl","SDL_ReadLE64","ptr",$src)
   Return $xSDL_ReadLE64[0]
EndFunc

Func SDL_ReadU8($src)
   Local $xSDL_ReadU8 = DllCall($SDL,"uint:cdecl","SDL_ReadU8","ptr",$src)
   Return $xSDL_ReadU8[0]
EndFunc

Func SDL_WriteBE16($dst,$val)
   Local $xSDL_WriteBE16 = DllCall($SDL,"ulong_ptr:cdecl","SDL_WriteBE16","ptr",$dst,"uint",$val)
   Return $xSDL_WriteBE16[0]
EndFunc

Func SDL_WriteBE32($dst,$val)
   Local $xSDL_WriteBE32 = DllCall($SDL,"ulong_ptr:cdecl","SDL_WriteBE32","ptr",$dst,"uint",$val)
   Return $xSDL_WriteBE32[0]
EndFunc

Func SDL_WriteBE64($dst,$val)
   Local $xSDL_WriteBE64 = DllCall($SDL,"ulong_ptr:cdecl","SDL_WriteBE64","ptr",$dst,"uint",$val)
   Return $xSDL_WriteBE64[0]
EndFunc

Func SDL_WriteLE16($dst,$val)
   Local $xSDL_WriteLE16 = DllCall($SDL,"ulong_ptr:cdecl","SDL_WriteLE16","ptr",$dst,"uint",$val)
   Return $xSDL_WriteLE16[0]
EndFunc

Func SDL_WriteLE32($dst,$val)
   Local $xSDL_WriteLE32 = DllCall($SDL,"ulong_ptr:cdecl","SDL_WriteLE32","ptr",$dst,"uint",$val)
   Return $xSDL_WriteLE32[0]
EndFunc

Func SDL_WriteLE64($dst,$val)
   Local $xSDL_WriteLE64 = DllCall($SDL,"ulong_ptr:cdecl","SDL_WriteLE64","ptr",$dst,"uint",$val)
   Return $xSDL_WriteLE64[0]
EndFunc

Func SDL_WriteU8($dst,$val)
   Local $xSDL_WriteU8 = DllCall($SDL,"ulong_ptr:cdecl","SDL_WriteU8","ptr",$dst,"uint",$val)
   Return $xSDL_WriteU8[0]
EndFunc

;Surface Functions
Func SDL_BlitScaled($src,$xSDL_Rect,$dst,$xSDL_Rect2)
   Local $xSDL_BlitScaled = DllCall($SDL,"int:cdecl","SDL_BlitScaled","ptr",$src,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",$dst,"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_BlitScaled[0]
EndFunc

Func SDL_BlitSurface($src,$xSDL_Rect,$dst,$xSDL_Rect2)
   Local $xSDL_BlitSurface = DllCall($SDL,"int:cdecl","SDL_BlitSurface","ptr",$src,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",$dst,"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_BlitSurface[0]
EndFunc

Func SDL_ConvertPixels($w,$h,$mat,$src,$pit,$dst,$dst2,$pit2)
   Local $xSDL_ConvertPixels = DllCall($SDL,"int:cdecl","SDL_ConvertPixels","int",$w,"int",$h,"uint",$mat,"ptr",$src,"int",$pit,"uint",$dst,"ptr",$dst2,"int",$pit2)
   Return $xSDL_ConvertPixels[0]
EndFunc

Func SDL_ConvertSurface($src,$fmt,$flags)
   Local $xSDL_ConvertSurface = DllCall($SDL,"ptr:cdecl","SDL_ConvertSurface","ptr",$src,"ptr",$fmt,"uint",$flags)
   Return $xSDL_ConvertSurface[0]
EndFunc

Func SDL_ConvertSurfaceFormat($src,$pix,$flags)
   Local $xSDL_ConvertSurfaceFormat = DllCall($SDL,"ptr:cdecl","SDL_ConvertSurfaceFormat","ptr",$src,"uint",$pix,"uint",$flags)
   Return $xSDL_ConvertSurfaceFormat[0]
EndFunc

Func SDL_CreateRGBSurface($flags,$w,$h,$d,$rm,$gm,$bm,$am)
   Local $xSDL_CreateRGBSurface = DllCall($SDL,"ptr:cdecl","SDL_CreateRGBSurface","uint",$flags,"int",$w,"int",$h,"int",$d,"uint",$rm,"uint",$gm,"uint",$bm,"uint",$am)
   Return $xSDL_CreateRGBSurface[0]
EndFunc

Func SDL_CreateRGBSurfaceFrom($pix,$w,$h,$d,$rm,$gm,$bm,$am)
   Local $xSDL_CreateRGBSurfaceFrom = DllCall($SDL,"ptr:cdecl","SDL_CreateRGBSurfaceFrom","ptr",$pix,"int",$w,"int",$h,"int",$d,"uint",$rm,"uint",$gm,"uint",$bm,"uint",$am)
   Return $xSDL_CreateRGBSurfaceFrom[0]
EndFunc

Func SDL_CreateRGBSurfaceWithFormat($flags,$w,$h,$d,$mat)
   Local $xSDL_CreateRGBSurfaceWithFormat = DllCall($SDL,"ptr:cdecl","SDL_CreateRGBSurfaceWithFormat","uint",$flags,"int",$w,"int",$h,"int",$d,"uint",$mat)
   Return $xSDL_CreateRGBSurfaceWithFormat[0]
EndFunc

Func SDL_CreateRGBSurfaceWithFormatFrom($pix,$w,$h,$d,$pit,$mat)
   Local $xSDL_CreateRGBSurfaceWithFormatFrom = DllCall($SDL,"ptr:cdecl","SDL_CreateRGBSurfaceWithFormatFrom","ptr",$pix,"int",$w,"int",$h,"int",$d,"int",$pit,"uint",$mat)
   Return $xSDL_CreateRGBSurfaceWithFormatFrom[0]
EndFunc

Func SDL_FillRect($dst,$xSDL_Rect,$col)
   Local $xSDL_FillRect = DllCall($SDL,"int:cdecl","SDL_FillRect","ptr",$dst,"ptr",DllStructGetPtr($xSDL_Rect),"uint",$col)
   Return $xSDL_FillRect[0]
EndFunc

Func SDL_FillRects($dst,$xSDL_Rect,$count,$col)
   Local $xSDL_FillRects = DllCall($SDL,"int:cdecl","SDL_FillRects","ptr",$dst,"ptr",DllStructGetPtr($xSDL_Rect),"int",$count,"uint",$col)
   Return $xSDL_FillRects[0]
EndFunc

Func SDL_FreeSurface($surf)
   Local $xSDL_FreeSurface = DllCall($SDL,"none","SDL_FreeSurface","ptr",$surf)
   Return $xSDL_FreeSurface[0]
EndFunc

Func SDL_GetClipRect($surf,$xSDL_Rect)
   Local $xSDL_GetClipRect = DllCall($SDL,"none","SDL_GetClipRect","ptr",$surf,"ptr",DllStructGetPtr($xSDL_Rect)
   Return $xSDL_GetClipRect[0]
EndFunc

Func SDL_GetColorKey($surf,$key)
   Local $xSDL_GetColorKey = DllCall($SDL,"int:cdecl","SDL_GetColorKey","ptr",$surf,"ptr",$key)
   Return $xSDL_GetColorKey[0]
EndFunc

Func SDL_GetSurfaceAlphaMod($surf,$al)
   Local $xSDL_GetSurfaceAlphaMod = DllCall($SDL,"int:cdecl","SDL_GetSurfaceAlphaMod","ptr",$surf,"ptr",$al)
   Return $xSDL_GetSurfaceAlphaMod[0]
EndFunc

Func SDL_GetSurfaceBlendMode($surf,$blend)
   Local $xSDL_GetSurfaceBlendMode = DllCall($SDL,"int:cdecl","SDL_GetSurfaceBlendMode","ptr",$surf,"ptr",$blend)
   Return $xSDL_GetSurfaceBlendMode[0]
EndFunc

Func SDL_GetSurfaceColorMod($surf,$r,$g,$b)
   Local $xSDL_GetSurfaceColorMod = DllCall($SDL,"int:cdecl","SDL_GetSurfaceColorMod","ptr",$surf,"ptr",$r,"ptr",$g,"ptr",$b)
   Return $xSDL_GetSurfaceColorMod[0]
EndFunc

Func SDL_LoadBMP_RW($src,$xfree)
   Local $xSDL_LoadBMP_RW = DllCall($SDL,"ptr:cdecl","SDL_LoadBMP_RW","ptr",$src,"int",$xfree)
   Return $xSDL_LoadBMP_RW[0]
EndFunc

Func SDL_LoadBMP($file)
   Return SDL_LoadBMP_RW(SDL_RW_FromFile($file,"rb"),1)
EndFunc

Func SDL_SaveBMP_RW($surf,$dst,$xfree)
   Local $xSDL_SaveBMP_RW = DllCall($SDL,"int:cdecl","SDL_SaveBMP_RW","ptr",$surf,"ptr",$dst,"int",$xfree)
   Return $xSDL_SaveBMP_RW[0]
EndFunc

Func SDL_SaveBMP($surf,$file)
   Return SDL_SaveBMP_RW($surf,SDL_RWFromFile($file,"wb"),1)
EndFunc

Func SDL_LockSurface($surf)
   Local $xSDL_LockSurface = DllCall($SDL,"int:cdecl","SDL_LockSurface","ptr",$surf)
   Return $xSDL_LockSurface[0]
EndFunc

Func SDL_LowerBlit($src,$xSDL_Rect,$dst,$xSDL_Rect2)
   Local $xSDL_LowerBlit = DllCall($SDL,"int:cdecl","SDL_LowerBlit","ptr",$surf,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",$dst,"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_LowerBlit[0]
EndFunc

Func SDL_LowerBlitScaled($src,$xSDL_Rect,$dst,$xSDL_Rect2)
   Local $xSDL_LowerBlitScaled = DllCall($SDL,"int:cdecl","SDL_LowerBlitScaled","ptr",$surf,"ptr",DllStructGetPtr($xSDL_Rect),"ptr",$dst,"ptr",DllStructGetPtr($xSDL_Rect2))
   Return $xSDL_LowerBlitScaled[0]
EndFunc

Func SDL_MUSTLOCK($surf)
   Local $xSDL_MUSTLOCK = DllCall($SDL,"bool:cdecl","SDL_MUSTLOCK","ptr",$surf)
   Return $xSDL_MUSTLOCK[0]
EndFunc

Func SDL_SetClipRect($surf,$xSDL_Rect)
   Local $xSDL_SetClipRect = DllCall($SDL,"bool:cdecl","SDL_SetClipRect","ptr",$surf,"ptr",DllStructGetPtr($xSDL_Rect))
   Return $xSDL_SetClipRect[0]
EndFunc

Func SDL_SetColorKey($surf,$flag,$key)
   Local $xSDL_SetColorKey = DllCall($SDL,"int:cdecl","SDL_SetColorKey","ptr",$surf,"int",$flag,"uint",$key)
   Return $xSDL_SetColorKey[0]
EndFunc

Func SDL_SetSurfaceAlphaMod($surf,$al)
   Local $xSDL_SetSurfaceAlphaMod = DllCall($SDL,"int:cdecl","SDL_SetSurfaceAlphaMod","ptr",$surf,"uint",$al)
   Return $xSDL_SetSurfaceAlphaMod[0]
EndFunc

Func SDL_SetSurfaceBlendMode($surf,$mode)
   Local $xSDL_SetSurfaceBlendMode = DllCall($SDL,"int:cdecl","SDL_SetSurfaceBlendMode","ptr",$surf,"ptr",$mode)
   Return $xSDL_SetSurfaceBlendMode[0]
EndFunc

Func SDL_SetSurfaceColorMod($surf,$r,$g,$b)
   Local $xSDL_SetSurfaceColorMod = DllCall($SDL,"int:cdecl","SDL_SetSurfaceColorMod","ptr",$surf,"uint",$r,"uint",$g,"uint",$b)
   Return $xSDL_SetSurfaceColorMod[0]
EndFunc

Func SDL_SetSurfacePalette($surf,$pal)
   Local $xSDL_SetSurfacePalette = DllCall($SDL,"int:cdecl","SDL_SetSurfacePalette","ptr",$surf,"ptr",$pal)
   Return $xSDL_SetSurfacePalette[0]
EndFunc

Func SDL_SetSurfaceRLE($surf,$flag)
   Local $xSDL_SetSurfaceRLE = DllCall($SDL,"int:cdecl","SDL_SetSurfaceRLE","ptr",$surf,"int",$flag)
   Return $xSDL_SetSurfaceRLE[0]
EndFunc

Func SDL_UnlockSurface($surf)
   Local $xSDL_UnlockSurface = DllCall($SDL,"none","SDL_UnlockSurface","ptr",$surf)
   Return $xSDL_UnlockSurface[0]
EndFunc

;SYSWM Function
;Duplicate?
;Func SDL_GetWindowWMInfo($win,$info)
 ;  Local $xSDL_GetWindowWMInfo = DllCall($SDL,"bool:cdecl","SDL_GetWindowWMInfo","ptr",$win,"ptr",$info)
  ; Return $xSDL_GetWindowWMInfo[0]
;EndFunc

;Clibpoard functions
Func SDL_GetClipboardText()
   Local $xSDL_GetClipboardText = DllCall($SDL,"ptr:cdecl","SDL_GetClipboardText")
   Return $xSDL_GetClipboardText[0]
EndFunc

Func SDL_HasClipboardText()
   Local $xSDL_HasClipboardText = DllCall($SDL,"bool:cdecl","SDL_HasClipboardText")
   Return $xSDL_HasClipboardText[0]
EndFunc

Func SDL_SetClipboardText($text)
   Local $xSDL_SetClipboardText = DllCall($SDL,"int:cdecl","SDL_SetClipboardText","ptr",$text)
   Return $xSDL_SetClipboardText[0]
EndFunc

;SDL Event Functions

;Get Platform
Func SDL_GetPlatform()
   Local $xSDL_GetPlatform = DllCall($SDL,"ptr:cdecl","SDL_GetPlatform")
   Return $xSDL_GetPlatform[0]
EndFunc

;CPU Functions
Func SDL_GetCPUCacheLineSize()
   Local $xSDL_GetCPUCacheLineSize = DllCall($SDL,"int:cdecl","SDL_GetCPUCacheLineSize")
   Return $xSDL_GetCPUCacheLineSize[0]
EndFunc

Func SDL_GetCPUCount()
   Local $xSDL_GetCPUCount = DllCall($SDL,"int:cdecl","SDL_GetCPUCount")
   If @error Then Return SetError(1, @error, -1)

  ;ConsoleWrite(StringFormat("CPUs: %i", $xSDL_GetCPUCount[0]) & @CRLF)
  Return $xSDL_GetCPUCount[0]
EndFunc

Func SDL_GetSystemRAM()
   Local $xSDL_GetSystemRAM = DllCall($SDL,"int:cdecl","SDL_GetSystemRAM")
   ;ConsoleWrite(StringFormat("RAM: %i", $xSDL_GetSystemRAM[0]) & @CRLF)
   If @error Then Return SetError(1, @error, -1)
   Return $xSDL_GetSystemRAM[0]
EndFunc

Func SDL_Has3DNow()
   Local $xSDL_Has3DNow = DllCall($SDL,"bool:cdecl","SDL_Has3DNow")
   Return $xSDL_Has3DNow[0]
EndFunc

Func SDL_HasAVX()
   Local $xSDL_HasAVX = DllCall($SDL,"bool:cdecl","SDL_HasAVX")
   Return $xSDL_HasAVX[0]
EndFunc

Func SDL_HasAVX2()
   Local $xSDL_HasAVX = DllCall($SDL,"bool:cdecl","SDL_HasAVX2")
   Return $xSDL_HasAVX[0]
EndFunc

Func SDL_HasAliVec()
   Local $xSDL_HasAltiVec = DllCall($SDL,"bool:cdecl","SDL_HasAltiVec")
   Return $xSDL_HasAltiVec[0]
EndFunc

Func SDL_HasMMX()
   Local $xSDL_HasMMX = DllCall($SDL,"bool:cdecl","SDL_HasMMX")
   Return $xSDL_HasMMX[0]
EndFunc

Func SDL_HasRDTSC()
   Local $xSDL_HasRDTSC = DllCall($SDL,"bool:cdecl","SDL_HasRDTSC")
   Return $xSDL_HasRDTSC[0]
EndFunc

Func SDL_HasSSE()
   Local $xSDL_HasSSE = DllCall($SDL,"bool:cdecl","SDL_HasSSE")
   Return $xSDL_HasSSE[0]
EndFunc

Func SDL_HasSSE2()
   Local $xSDL_HasSSE2 = DllCall($SDL,"bool:cdecl","SDL_HasSSE2")
   Return $xSDL_HasSSE2[0]
EndFunc

Func SDL_HasSSE3()
   Local $xSDL_HasSSE3 = DllCall($SDL,"bool:cdecl","SDL_HasSSE3")
   Return $xSDL_HasSSE3[0]
EndFunc

Func SDL_HasSSE41()
   Local $xSDL_HasSSE41 = DllCall($SDL,"bool:cdecl","SDL_HasSSE41")
   Return $xSDL_HasSSE41[0]
EndFunc

Func SDL_HasSSE42()
   Local $xSDL_HasSSE42 = DllCall($SDL,"bool:cdecl","SDL_HasSSE42")
   Return $xSDL_HasSSE42[0]
EndFunc

;Cleanup
DllClose($SDL)